### ISSUE TITLE
Feature request: Pagination

### ISSUE THREAD

**Issue by joeydebreuk** [strawberry-graphql/strawberry-graphql-django#11]
Maybe its an idea to take (optional) pagination in mind. At the root query, but also at related queries. 

This is what I'm using now: https://gist.github.com/joeydebreuk/2e1333fb8da82220bca5300ee81d225c

**Comment by la4de** [comment]
I like that. Maybe we could start with something simple like offset and count parameters and extend it later.

**Comment by la4de** [comment]
We have simple offset and limit pagination in features/class-api branch. Feel free to try.

**Comment by la4de** [comment]
See pull request #30. Basic pagination support will be part of v0.2 release.
