### ISSUE TITLE
Feature request: A better way to filter

### ISSUE THREAD

**Issue by joeydebreuk** [strawberry-graphql/strawberry-graphql-django#12]
The filter `filters: [String!]` couples the query directly to the models' shape, and without schema validation. This can cause many issues, eg:

- To use filters you need to know the shape of the Django models.
- If there are changes in the Django model, the existing filters might break, without being able to check this with schema validation

I think we need to find a better alternative. Maybe we can use [Django Filters](https://django-filter.readthedocs.io/en/stable/ref/filterset.html?highlight=FilterSet).

**Comment by la4de** [comment]
I agree with you. The current approach was the easiest way to get it done. That's fine for prototype but we definitely want to change that soon. I think that's one part where you could help me by contributing the project. :)

**Comment by joeydebreuk** [comment]
I'll work on something

**Comment by la4de** [comment]
Thanks @joeydebreuk. I drafted following API in #10. Are you happy with that or planning something else?
```
query {
  users(filters: { name__contains: "user" }) {
    id
    name
    tags(filters: { or: { id__gt: 20, not: { id__in: [5, 7, 10] } } }) {
      id
    }
  }
}
```

**Comment by joeydebreuk** [comment]
Ah ok! I was more thinking to leave the logic as much to the filter definition in the backend as possible. eg:
```
class UserFilter(django_filters.FilterSet):
    search = CharFilter(field_name="name",  lookup_expr='icontains')
    tagged_with = NumberInFilter(field_name='tags', lookup_expr='in')
```

```
query {
  users(filters: { search: "joey", taggedWith: ["tag1", "tag2"] }) {
    id
    name
    tags {
      id
    }
  }
}
```
Django filters can do a lot of the work for us. [Also possible to automatically generate filters](https://django-filter.readthedocs.io/en/stable/ref/filterset.html#disable-filter-fields-with-exclude). We just map filter sets to a filter input.

**Comment by joeydebreuk** [comment]
https://github.com/strawberry-graphql/strawberry-graphql-django/pull/15

Wrote everything in 1 file for now, but you get the point.

**Comment by la4de** [comment]
> Ah ok! I was more thinking to leave the logic as much to the filter definition in the backend as possible. eg:

Yes, let's start with that approach


> Django filters can do a lot of the work for us. [Also possible to automatically generate filters](https://django-filter.readthedocs.io/en/stable/ref/filterset.html#disable-filter-fields-with-exclude). We just map filter sets to a filter input.

Great idea!

**Comment by la4de** [comment]
Filtering support have been implemented and merged to main branch. Thank you @joeydebreuk!
