### ISSUE TITLE
Django type interface from docs doesn't work

### ISSUE THREAD

**Issue by ryou90** [strawberry-graphql/strawberry-graphql-django#120]
Hi :)
it seems that the interface attribute in the code example from [Docs](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/docs/references/resolvers.md) is not working.

Is there an alternative way to declare interfaces?

**Comment by Kazion500** [comment]
can you share code snippet for your implementation.
Just so you add more context to your question.

**Comment by ryou90** [comment]
First of all there is a mistake in the doc description.
type**S** does not exist.

```python
@strawberry.django.types(models.Fruit, interface=True)
class Fruit:
    id: auto
    name: auto
```

When using the interface attribute, i got an error: 

> type() got an unexpected keyword argument 'interace'

My Code:

```python

#models.py

class Feed(Model):
    id = PositiveBigIntegerField("ID", primary_key=True)
    title = CharField("Title", blank=False, max_length=80)
    feedname = SlugField("Slug name", blank=False, max_length=80)
    description = CharField("Titel", blank=False, max_length=300)`
    latitude = FloatField("Latitude", blank=True, null=True)
    longitude = FloatField("Longitude", blank=True, null=True)

#types.py

@strawberry.django.type(models.Feed, interface=True)
class Feed:
    id: auto
    title: auto
    feedname: auto
    description: auto

@strawberry.django.type(models.Feed)
class LocationFeed(Feed):
    latitude: auto
    longitude: auto

@strawberry.django.type(models.Feed)
class TopicFeed(Feed):
    pass
```

**Comment by hiporox** [comment]
@ryou90 The inheritance of types is kinda wonky. You can get it to work if you define the same fields on the interface again on the type definition that is inheriting

**Comment by ryou90** [comment]
Thx for the hint. Try it but got the same error again:

> type() got an unexpected keyword argument 'interface'

**Comment by bellini666** [comment]
@ryou90 the type hints need to be improved there, but the argument is the same as `strawberry.type`, you should use `is_interface=True` instead of `interface=True`

**Comment by ryou90** [comment]
Perfect, that solved my problem . Thank you:)
Now it needs only a fix for the docs.

**Comment by bellini666** [comment]
> Perfect, that solved my problem . Thank you:) Now it needs only a fix for the docs.

Feel free to open a PR and I'll gladly review it :)
