### ISSUE TITLE
Dispute on nullability 

### ISSUE THREAD

**Issue by FlickerSoul** [strawberry-graphql/strawberry-graphql-django#128]
I think there is a problem regarding generating nullable types but I'm not sure. 

Here is my situation. So I have three models, `A`, `B`, `C` listed below. `A` is a foreign key of `B`, and is in m2m rel with `C` 

```python
from __future__ import annotations

from typing import List

import strawberry
import strawberry_django
from django.core.management import BaseCommand
from django.db import models
from strawberry import auto
from strawberry.printer import print_schema


class A(models.Model):
    pass


class B(models.Model):
    a = models.ForeignKey(A, on_delete=models.PROTECT, related_name="bs", null=False)
    s = models.TextField(null=False)
    sn = models.TextField(null=True)


class C(models.Model):
    a = models.ManyToManyField(A, related_name="cs", null=False)


@strawberry_django.type(A)
class AType:
    bs: List[BType]
    cs: List[CType]


@strawberry_django.type(B)
class BType:
    a: AType
    s: auto
    sn: auto


@strawberry_django.type(C)
class CType:
    a: List[AType]


@strawberry.type
class Query:
    @strawberry.field
    def get_a(self, info) -> List[AType]:
        return A.objects.all()

```

When I declare my type for `A`, I explicitly want the reverse reference `bs` to be the type `[BType!]!`, and `cs` to be the type `[CType!]!`. But if I print the schema, the type resolution gives me `[BType!]` and `[CType!]` instead. 

```graphql
type AType {
  bs: [BType!]
  cs: [CType!]
}

type BType {
  a: AType!
  s: String!
  sn: String
}

type CType {
  a: [AType!]!
}

type Query {
  getA: [AType!]!
}
```

But curiously, the type of `a` in `CType` is correct. 

When I look into the code, the nullability of `bs` and `cs` should be assign [here](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/ab665de24efae7bf7fd31183eecfd931a30963f8/strawberry_django/type.py#L78), which is determined by the function [`is_optioinal`](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/9641f70517141e5001cb573adbf23fac059fdade/strawberry_django/fields/types.py#L168). When a field is not an input nor partial, the code checks if the field can be null (the `null=True` kw arg in the field decleration I think ), and assigns nullability to the annotation. 

I found it problematic since if a field is `ManyToManyRel` or `ManyToOneRel`, there doesn't seem to exist a way to modify the nullability of the rel. I'm not very familiar with Django, and to my best knowledge I can't remember the value carried in these two kinds of rels can ever be `null`/`None`. 

I hope this makes sense :)

**Comment by FlickerSoul** [comment]
Adding type checks seem to work well? :) 

```python
def is_optional(model_field, is_input, partial):
    if partial:
        return True
    if not model_field:
        return False
    if is_input:
        if isinstance(model_field, fields.AutoField):
            return True
        if isinstance(model_field, fields.reverse_related.OneToOneRel):
            return model_field.null
        if model_field.many_to_many or model_field.one_to_many:
            return True
        has_default = model_field.default is not fields.NOT_PROVIDED
        if model_field.blank or has_default:
            return True
    # what's changed 
    if not isinstance(model_field, (fields.reverse_related.ManyToManyRel, fields.reverse_related.ManyToOneRel)):
        if model_field.null:
            return True
    return False

```

**Comment by bellini666** [comment]
Hey @FlickerSoul ,

You are right, the list of related objects are never null in this case, but simply an empty list if there aren't any results.

Would you like to open a PR with your proposed change? I'll gladly review it :)
