### ISSUE TITLE
Support for model @property or callable access

### ISSUE THREAD

**Issue by benhowes** [strawberry-graphql/strawberry-graphql-django#134]
In the case you have a model with properties, e.g.

```python

class MyUser(AbstractUser):

    @property
    def activation_state_display(self) -> str:
        return "some state"
    
```

It would be handy to be able to expose properties and (within reason) methods via this package, e.g.

```python

@strawberry.django.type(MyUser)
class MyUserType:
   # Property access
   activation_state_display: str # Could this be typed as `auto`?
   # Method access
   full_name: str = field(field_name="get_full_name")
```

Currently `get_model_field` does not support this use case, but I suspect it could? 

Is there an appetite to implement some or all of this suggestion? I'd be happy to create a PR if so.

## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

**Comment by bellini666** [comment]
This should be fixed in [v0.10.0](https://github.com/strawberry-graphql/strawberry-graphql-django/releases/tag/v0.10.0)
