### ISSUE TITLE
support django 4.1 async ORM

### ISSUE THREAD

**Issue by nrbnlulu** [strawberry-graphql/strawberry-graphql-django#156]
## Feature Request Type
Support for django 4.1 async ORM.
- [x] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
Starting from [django 4.1](https://docs.djangoproject.com/en/dev/releases/4.1/#asynchronous-orm-interface) there is an async version of the ORM.  
We won't need to wrap resolvers with `sync_to_async()` and this will improve performance significantly.

**Comment by bellini666** [comment]
The only issue here is that to change this we need to drop support for django 4.0 or less.

Also, the only benefit of using it currently is less code written, since the async interface is actually just a `sync_to_async` decorated version of the original. I actually have a wrapper around `QuerySet` in my personal projects that does exactly that, and I'm very happy that when I upgrade to django 4.1 I'll be able to drop it :)

**Comment by nrbnlulu** [comment]
> The only issue here is that to change this we need to drop support for django 4.0 or less.
1. I think some runtime version checking can solve this no?
2. we can create a new branch for this.
Though I agree it would be a nightmare to maintain.
 
 > since the async interface is actually just a sync_to_async decorated version of the original.
 What? so the async ORM in 4.1 isn't really async?

**Comment by bellini666** [comment]
> What? so the async ORM in 4.1 isn't really async?

They are not. Check the implementation of some methods, for example `QuerySet.aget`[https://github.com/django/django/blob/main/django/db/models/query.py#L661] is basically this:

```python
async def aget(self, *args, **kwargs):
    return await sync_to_async(self.get)(*args, **kwargs)
```

But with that, as soon as they start using database drivers that actually support asyncio (e.g. psycopg3 and/or asyncpg for postgres, aiosqlite for sqlite) then they can simply replace those with actual calls to the asynchronous driver without requiring everyone to change their codes.

**Comment by nrbnlulu** [comment]
I see, so this is really useless currently heh. Thanks!

**Comment by bellini666** [comment]
> I see, so this is really useless currently heh. Thanks!

Not really. It is a shortcut currently, but it would not make a difference right now for us here unfortunately.

When the code is really using asynchronous database drivers, we can change how we deal with it here and avoid the extra thread `sync_to_async` creates
