### ISSUE TITLE
Circular dependency issue with multiple type files

### ISSUE THREAD

**Issue by tracykm** [strawberry-graphql/strawberry-graphql-django#171]
I'm trying to migrate a big project from graphene to strawberry. The type inference in graphene allowed me to get around circular dependencies. I was hoping `auto` would allow the same thing here, but everything comes out `DjangoModelType`. So I went to add the types more explicitly and now I either run into a circular dependency or an error that type is not defined.

As an example, is there a way for me to have `users/types.py` and `teams/types.py` as separate files?
```python
@strawberry_django.type(User)
class UserType:
    id: auto
    email: auto
    team: "TeamType"


@strawberry_django.type(Team)
class TeamType:
    id: auto
    name: auto
    users: list[UserType]

```

error with import
```
ImportError: cannot import name 'UserType' from partially initialized module 'gql.example' (most likely due to a circular import) (/workspace/gql/example.py)
```

error with string type
```
TypeError: UserType fields cannot be resolved. Could not resolve the type of `team'. Check that the class is accessible from the global module scope.
```

**Comment by bellini666** [comment]
Hi @tracykm ,

You need to use `LazyType` for that: https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/lazy_type.py

For example:

```python
@strawberry_django.type(User)
class UserType:
    id: auto
    email: auto
    team: strawberry.LazyType["TeamType", "teams.types"]


@strawberry_django.type(Team)
class TeamType:
    id: auto
    name: auto
    users: list[UserType]
```

**Comment by tracykm** [comment]
@bellini666 Awesome! I was hoping I was missing something
