### ISSUE TITLE
Software license 

### ISSUE THREAD

**Issue by Wartijn** [strawberry-graphql/strawberry-graphql-django#18]
I noticed this project doesn't have a license yet. Without one it's problematic for companies (and actually anyone) to use this project. Can one be added? 

I suggest using the MIT license since it's permissive and short and it's what Strawberry uses

**Comment by patrick91** [comment]
👍 for MIT, @la4de does that sound ok to you?

**Comment by la4de** [comment]
There is MIT license file in v0.0.x branch but for some reason it got lost during v0.1 development. I'll push it back :)
