### ISSUE TITLE
Filters are broken

### ISSUE THREAD

**Issue by capital-G** [strawberry-graphql/strawberry-graphql-django#182]
## Describe the Bug

Either I have a complete missunderstanding of what filters do in Graphql (sry, currently trying to learn graphql via strawberry) or there is a bug in its django implementation.

Firing up [the example](https://github.com/strawberry-graphql/strawberry-graphql-django/tree/main/examples/django) and try to filter dynamically (where to my understanding graphql shall excel rest?) it does not work as expected as the left query produces the right response

<img width="941" alt="grafik" src="https://user-images.githubusercontent.com/8267062/192641694-185a7226-1ac6-4efd-b6e6-6542a2f7556b.png">

Inserting any kind of query filters always result in an unfiltered queryset.

## System Information

 - Operating system:
 ```shell
❯ uname -a
Darwin xxx.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
```
 - Strawberry version (if applicable) - based upon the modified example (see #181 )
```shell
name = "strawberry-graphql"
version = "0.133.0"

[...]

[[package]]
name = "strawberry-graphql-django"
version = "0.5.1"
```

## Additional Context

It would be nice to provide some hint in the documentation on how filters work because there isn't a hint on how to write the querry or any external resources and I figured out you can compose the query via GUI.

**Comment by g-as** [comment]
Strawberry 0.132.1 broke a lot of stuff, including filtering:

https://github.com/strawberry-graphql/strawberry/pull/2194
https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1

**Comment by capital-G** [comment]
Thanks for the hint :)
Maybe to avoid these kind of bugs it would be a good practice to keep the versions to strawberry-core fixed?
I installed this extension via pip and got

```shell
venv ❯ pip freeze | grep strawberry
strawberry-graphql==0.132.1
strawberry-graphql-django==0.5.1
```

which is strange as https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1 was released 5 days ago but https://github.com/strawberry-graphql/strawberry-graphql-django/releases/tag/v0.5.1 16 days ago.

Maybe it is therefore a good idea to keep this version fixed and increment them via commits which run the test pipeline?

https://github.com/strawberry-graphql/strawberry-graphql-django/blob/5d85c4b43842cb401506c86954a33e94251e53c8/pyproject.toml#L29

**Comment by jkimbo** [comment]
As the author of 
https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1 I'm very sorry for breaking things unexpectedly. I'll try and take a look to see why filters stopped working. 

@g-as was there anything else that broke for you? 

@capital-G I think the intention was to eventually merge strawberry Django into the main strawberry repo so that breakages would be spotted much earlier. I'm not sure if that is still the intention.

**Comment by g-as** [comment]
@jkimbo 

No worries, thanks for reacting quickly.

Inputs (create/update) now fail as well:
```
Traceback (most recent call last):
  File "/home/backend/.venv/lib/python3.9/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/home/backend/.venv/lib/python3.9/site-packages/strawberry/extensions/base_extension.py", line 42, in resolve
    return _next(root, info, *args, **kwargs)
  File "/home/backend/.venv/lib/python3.9/site-packages/strawberry/extensions/base_extension.py", line 42, in resolve
    return _next(root, info, *args, **kwargs)
  File "/home/backend/.venv/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 421, in _get_basic_result
    return field.get_result(_source, info=None, args=[], kwargs={})
  File "/home/backend/.venv/lib/python3.9/site-packages/strawberry_django/resolvers.py", line 25, in wrapper
    return resolver(*args, **kwargs)
  File "/home/backend/.venv/lib/python3.9/site-packages/strawberry_django/mutations/fields.py", line 51, in get_result
    return self.resolver(info=info, source=source, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
TypeError: resolver() missing 1 required positional argument: 'data'
```

From what I've gathered, the generic mutations of strawberry-django are now `basic_field`, and the arguments added by strawberry-django (`data`, `queryset`), are ignored or not processed.

**Comment by jkimbo** [comment]
Found the issue and fixed it in https://github.com/strawberry-graphql/strawberry-graphql-django/pull/183
