### ISSUE TITLE
Proposal for class-oriented API

### ISSUE THREAD

**Issue by la4de** [strawberry-graphql/strawberry-graphql-django#20]
Would it make sense to define all fields always in class? I had also few other improvement ideas for authentication and filters. We have functional implementation in `feature/class-api` branch which is still under development.

First draft of doc is available, please take a look and leave your comments. https://github.com/strawberry-graphql/strawberry-graphql-django/blob/feature/class-api/docs/index.md

Changelog:
* 9.4.2021 - initial draft
* 10.4.2021 - API adjustments
* 4.5.2021 - Add couple of new examples and update existing ones
* 12.5.2021 - Add link to docs and update filtering api

types
```python
import strawberry_django
from strawberry_django import auto

@strawberry_django.type(models.User)
class User:
    id: auto
    name: auto
    car: List['Car'] = strawberry_django.field(field_name='car_set')

@strawberry_django.type(models.Car)
class Car:
    id: auto
    model: auto
    owner: User

@strawberry_django.input(models.User)
class UserInput:
    name: auto

# type inheritance
@strawberry_django.input(models.User, partial=True)
class UserPartialInput(UserInput):
    pass
```

queries and mutations
```python
from strawberry_django import mutations

@strawberry.type
class Query:
    user: User = strawberry_django.field()
    users: List[User] = strawberry_django.field(filters=UserFilter)
    cars: List[Car] = strawberry_django.field(filters=CarFilter, pagination=True)

@strawberry.type
class Mutation:
    create_user: User = mutations.create(UserInput)
    update_user: User = mutations.update(UserPartialInput)
    update_users: List[User] = mutations.update(UserPartialInput, filters=UserFilter, many=True)
    delete_users: List[User] = mutations.delete(filters=UserFilter, many=True)
```

authentication
```python
from strawberry_django import auth

@strawberry.type
class Query:
    me: User = auth.current_user()

@strawberry.type
class Mutation:
    login: User = auth.login()
    logout = auth.logout()
```

filters
```python
@strawberry_django.filters.filter(models.Car, lookups=True)
class CarFilter:
    id: auto
    model : auto
    search: str

    # question: how should we define the filter function for special fields?
    def filter_search(self, queryset):
        return queryset.filters(name__contains=self.search)
```

**Comment by patrick91** [comment]
I don't dislike this, my only concert is that might be a bit more confusing than a `fields` argument (as you'd do on django rest framework and django forms)

the other thing, should consider a way of automatically exposing all the fields? 🤔 

/cc @BryceBeagle @jkimbo

**Comment by patrick91** [comment]
oh, also do we need:

```
@strawberry_django.query
@strawberry_django.mutation
```

? 

it sounds like we could use `@strawberry.type` directly

**Comment by joeydebreuk** [comment]
Good idea IMO. Easier to read, because user doesnt have to add the fields passed to `strawberry_django.type` and the declared class fields together to see what fields are available.

Imagine changelog for adding description.
Old api:
```python
@strawberry_django.type(models.User, fields=("id", "name", ))
class User:
    pass
```

to 

```python
@strawberry_django.type(models.User, fields=("name", ))
class User:
    id: strawberry.ID = ...
```

or new API

```python
@strawberry_django.type(models.User)
class User:
    id: auto
    name: auto
```
to


```python
@strawberry_django.type(models.User)
class User:
    id: auto = ...
    name: auto
 ```
 
 But the pro of the old API is, you can do something like this:
 ```python
 
 readonly_fields = (...)
 update_fields= (...)
 
@strawberry_django.type(models.User, fields=(*readonly_fields, *update_fields))
class UserType:
    pass
    
@strawberry_django.input(models.User, fields=update_fields)
class UserUpdate:
    pass
        
```

**Comment by la4de** [comment]
I'd propose to drop `fields` parameter from `strawberry_django.field` if we decide to go with class-oriented API.

Is anyone against that?

**Comment by la4de** [comment]
We are currently working on that. Code is still under development but it's already available in https://github.com/strawberry-graphql/strawberry-graphql-django/tree/feature/class-api branch if someone wants to take a look or try it :)

**Comment by adsharma** [comment]
https://www.python.org/dev/peps/pep-0647/ has the notion of type guards. Getting this done via static type checkers seems preferable over writing validators.

Having said that it's not clear that the PEP above has enough to specify all the constraints needed.

**Comment by la4de** [comment]
> https://www.python.org/dev/peps/pep-0647/ has the notion of type guards. Getting this done via static type checkers seems preferable over writing validators.
> 
> Having said that it's not clear that the PEP above has enough to specify all the constraints needed.

Do you have example how this could be used with class oriented API?

**Comment by adsharma** [comment]
It's not clear that this feature is usable by end users just yet. It seems to be designed for type checkers like mypy/pyright. Someone on python discord was speculating about implementing refinement types using TypeGuards.

The specific example discussed was:

```
from dataclasses import dataclass
from typing import Any, Optional, TypeGuard

class LessThan10(float):
    pass

def is_LessThan10(x: float) -> TypeGuard[LessThan10]:
    return x < 10.0

@dataclass
class Thing:
    x: LessThan10
    y: float
```

I would like a type checker to be able to detect that Thing(20, 1) is a type error.

@erictraut would know, but I'm not sure if I can tag him here.

**Comment by la4de** [comment]
This will be part of v0.2 release. See pull request #30. Let's continue discussion there.
