### ISSUE TITLE
Field annotation auto breaks when upgrading to Strawberry 0.139.0

### ISSUE THREAD

**Issue by ekalvi** [strawberry-graphql/strawberry-graphql-django#205]
## Describe the Bug
After upgrading to Strawberry 0.139.0 any `strawberry.django.type` classes that use the `auto` type will fail with error. See the recent release: https://github.com/strawberry-graphql/strawberry/releases/tag/0.139.0

**Example**

```
strawberry-graphql==0.139.0
strawberry-graphql-django==0.7.1
```

```python
@strawberry.django.type(models.Service)
class Service:
    id: auto
```

```
TypeError: Service fields cannot be resolved. Unexpected type 'auto'
```

## System Information

- Operating system: macOS Monterey version `12.6`
- Strawberry version (if applicable): `0.139.0`
- `strawberry-graphql` version (if applicable): `0.7.1`

## Additional Context

The Strawberry 0.139.0 release just went out Nov 4 @ 11am ET. It is very new.

**Comment by patrick91** [comment]
@ekalvi thanks for the report! I'll take a look!
