### ISSUE TITLE
After update to version 0.8 the GraphQL type of field with method resolver is generated as 'DjangoModelType'

### ISSUE THREAD

**Issue by Zlira** [strawberry-graphql/strawberry-graphql-django#209]
## Describe the Bug
Given the [models](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/examples/django/app/models.py) and other definitions from the example app, if I declare the `Fruit` type as following:
```python
from strawberry import auto, field

@strawberry_django.type(models.Fruit)
class Fruit:
    id: auto
    name: auto

    @field
    def color(self, info) -> "Color":
        # some additional logic here
        return self.color
```
The generated GraphQL type of the `color` field is `DjangoModelType` instead of `Color`:
```graphql
type Fruit {
  id: ID!
  name: String!
  color: DjangoModelType
}
```
I think, the work-around would be to declare `get_color` as a standalone function and then do this:
```python 
class Fruit:
    ...
    color: "Color" = field(resolver=get_color)
```
But the default behaviour seems unexpected to me.

## System Information

 - Operating system: Fedora Linux 36
 - Strawberry version: `strawberry-graphql==0.139.0`

**Comment by bellini666** [comment]
@patrick91 maybe something related to the issue you fixed last week? I'll try to take a look at this tomorrow

**Comment by patrick91** [comment]
I think so! That's annoying, also strange that we didn't find it in the tests 🤔

**Comment by patrick91** [comment]
@Zlira can you show us where Color is imported from?

**Comment by Zlira** [comment]
@patrick91 It wasn't imported, I just edited the definition of the `Fruit` type in the [example](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/examples/django/app/types.py#L49) app. The `Color` is a few lines below that.

Anyway, here's a smaller schema that reproduces the same behaviour (the [models](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/examples/django/app/models.py) are from the same app):
```python
import strawberry
import strawberry_django
from strawberry import auto, field

from . import models


@strawberry_django.type(models.Color)
class Color:
    id: auto
    name: auto


@strawberry_django.type(models.Fruit)
class Fruit:
    id: auto
    name: auto

    @field
    def color(self, info) -> "Color":
        # some additional logic here
        return self.color


@strawberry.type
class Query:
    fruit: Fruit = strawberry_django.field()


schema = strawberry.Schema(query=Query)
``` 
And the SDL for this schema is:
```graphql
type Query {
  fruit(pk: ID): Fruit!
}

type Fruit {
  id: ID!
  name: String!
  color: DjangoModelType
}

type DjangoModelType {
  pk: ID!
}
```

**Comment by bellini666** [comment]
Apparently there are two issues here:

1) Because the type annotation gets resolved before the resolver itself, we can't just force `auto` on unannotated fields (which is the case of fields without resolvers), otherwise it will be used and resolved to a generic `DjangoModelType`

2) When creating the type, the code that parses the fields could set their annotation as `UNRESOLVED` when using forward refs.

[This PR](https://github.com/strawberry-graphql/strawberry-graphql-django/pull/212) solves both issues. Can you take a look @patrick91 ?
