### ISSUE TITLE
Relational fields in create and update mutations

### ISSUE THREAD

**Issue by la4de** [strawberry-graphql/strawberry-graphql-django#21]
Let's start discussion about schema generation for create and update mutation. We need an API to update relational fields with mutations. Here is one idea how this could be done. I got inspiration from here: https://docs.fauna.com/fauna/current/api/graphql/relations#create

## create
```graphql
# create object and create, add or set relations
  createUser(data: {
    
    # one to one relation
    group: {
      # set by using primary key
      set: { id: 1 }
      set: 1  # question, should we accept also id/pk?
      # set existing object, filters have to be set so that there is only one matching object (will be implemented later)
      set: { username: "friend" }
      # create new object and add it to the user (will be implemented later)
      create: { name: "best friend" }
    }
    
    # many to many relation
    groups: {
      # add existing objects, can be used together with create
      add: [{ id: 1}, { id: 2 }],
      add: [1, 2],  # question, should we accept also list of id/pk values?
      # set, cannot be used together with create or add
      set: [{ id: 3 }, { id: 4 }],
      # create new objects along with user  (will be implemented later)
      create: [
        { name: "group 1" }
        { name: "group 2" }
      ],
    }
  }) {
    groups {
      id
      name
    }
  }
```

## update
```graphql
  # update relation field
  updateUser(data: { 

    # one to one relation
    group: {
      # set primary key
      set: 1
      # clear user
      set: null
      # create new object and add it to the user (will be implemented later)
      create: { name: "best friend" }
    }

    # many to many relation
    groups: {
      # add new groups
      add: [{ id: 1}, { id: 2 }],
      # remove groups
      remove: [{ id: 3 }, { id: 4 }],
      # set the list of objects, cannot be used together with create, add or remove
      set: [{ id: 3 }, { id: 4 }],
      # clear all objects
      set: [],
      # create and add objects (will be implemented later)
      create: [
        { name: "new group" }
      ],
    }) {
    groups {
      id
      name
    }
  }
}
```

**Comment by 2malh** [comment]
I'm still very new to Django/Python but here are some notes to consider:

While in Django I'm using the AutoBigField as PK I exclusively share an UUID to the frontend so setting the correct pk via default_fields or query to lookup is crucial.

I'm having quite a few many-to-many fields implemented via a 'through' intermediate model. So adding this into the mutation would be nice. So I guess there would have to be a couple of nested mutations. Here "assignees" is a intermediate model. So if I understand it correctly I first would have to create/get a task, load up the users/teams and then create/update the corresponding model "task_assignments" which has ForeignKeys to the models User and Task and set the corresponding role in the rrespective fields.

```gql
mutation updateTask( data: {
  task(uuid: $uuid) {
    name: "new name",
    assignees: {
      user1: {
        "user1_uuid": $user1_uuid,
        "user1_role": $user1_role
        },
      user2: {
        "user2_uuid": $user2_uuid,
        "user2_role": $user2_role
        },
      team1: {
        "team1_uuid": $team1_uuid,
        "team1_role": $team1_role
      }
    }
  }
}
```

On the matter of multiple and/or nested mutations I think this is important to consider (although I'm not sure if that's handled by GraphQL-core: "While query fields are executed in parallel, mutation fields run in series, one after the other.
This means that if we send two incrementCredits mutations in one request, the first is guaranteed to finish before the second begins, ensuring that we don't end up with a race condition with ourselves." (quoted from https://graphql.org/learn/queries/)

Also, besides create, update and I quite like the idea of the "upsert"-mutation that [Hasura offers](https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/index.html). [Prisma.io](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#create-1) has this mutation type as well. Maybe it's worth having a look if they're good for some more inspiration.

**Comment by la4de** [comment]
> While in Django I'm using the AutoBigField as PK I exclusively share an UUID to the frontend so setting the correct pk via default_fields or query to lookup is crucial.



> I'm having quite a few many-to-many fields implemented via a 'through' intermediate model. So adding this into the mutation would be nice. So I guess there would have to be a couple of nested mutations. Here "assignees" is a intermediate model. So if I understand it correctly I first would have to create/get a task, load up the users/teams and then create/update the corresponding model "task_assignments" which has ForeignKeys to the models User and Task and set the corresponding role in the rrespective fields.

Maybe we could use following syntax to pass through_default for django.
```graphql
{
  set: [ ... ],
  throughDefault: { ... }
}
````

> ```graphql
> mutation updateTask( data: {
>   task(uuid: $uuid) {
>     name: "new name",
>     assignees: {
>       user1: {
>         "user1_uuid": $user1_uuid,
>         "user1_role": $user1_role
>         },
>       user2: {
>         "user2_uuid": $user2_uuid,
>         "user2_role": $user2_role
>         },
>       team1: {
>         "team1_uuid": $team1_uuid,
>         "team1_role": $team1_role
>       }
>     }
>   }
> }
> ```

That's also one option. We could accept list of related objects and values of "through" fields.


> On the matter of multiple and/or nested mutations I think this is important to consider (although I'm not sure if that's handled by GraphQL-core: "While query fields are executed in parallel, mutation fields run in series, one after the other.
> This means that if we send two incrementCredits mutations in one request, the first is guaranteed to finish before the second begins, ensuring that we don't end up with a race condition with ourselves." (quoted from https://graphql.org/learn/queries/)

Need to investigate how the graphql core and strawberry work today.

> Also, besides create, update and I quite like the idea of the "upsert"-mutation that [Hasura offers](https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/index.html). [Prisma.io](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#create-1) has this mutation type as well. Maybe it's worth having a look if they're good for some more inspiration.

Interesting idea. Need to thing about that.

**Comment by la4de** [comment]
Create and update mutations have been to follow that syntax updated in #30. This will be part of v0.2 release.

Let's created new tickets for other features if needed.
