### ISSUE TITLE
GraphQLError with property field in v0.8.2

### ISSUE THREAD

**Issue by blueyed** [strawberry-graphql/strawberry-graphql-django#215]
With v0.8.2 (due to https://github.com/strawberry-graphql/strawberry-graphql-django/commit/d2ad144f51a3fd66228655ee2ae9b2718b78e377, added via https://github.com/strawberry-graphql/strawberry-graphql-django/pull/214) I am seeing an error with a field that is a property on the model:

> GraphQLError("Field 'fooProp' argument 'pk' of type 'ID!' is required, but it was not provided.")

```python
@django_type(models.Bar, filters=BarFilter, pagination=True)
class Bar:
    foo_prop: Foo | None = field(
        only=["foo__status"],
    )
```

/cc @benjaminderei @stygmate

**Comment by bellini666** [comment]
Hey @blueyed . Based on the fact that you are passing `only=["foo__status"]`, you are probably using `strawberry_django_plus`, correctly? If so, does the same issue happen if you use the `type` decorator and the `field` from `strawberry_django_plus`?

**Comment by blueyed** [comment]
> Based on the fact that you are passing `only=["foo__status"]`, you are probably using `strawberry_django_plus`, correctly?

Yes.

> If so, does the same issue happen if you use the `type` decorator and the `field` from `strawberry_django_plus`?

Yes.
Both when using `strawberry_django.type` on the class, and `strawberry_django.field` for the field (without `only` then).

(btw, it reminded me of https://github.com/blb-ventures/strawberry-django-plus/issues/55 btw, where the error is the same)

**Comment by bellini666** [comment]
@blueyed do you have a minimal reproducible example so that I can use to try to understand what might be causing the issue?

**Comment by illia-v** [comment]
0.8.2 caused a similar issue for me too.

This is a simplified extract of the code

```python
class Foo(models.Model):
    pass


class Bar(models.Model):    
    def get_foo(self) -> Foo:
        return Foo.objects.first()


@strawberry.django.type(Bar)
class BarType:
    get_foo: FooType = strawberry.field(name="foo")
```

**Comment by blueyed** [comment]
@bellini666 does the minimal example work for you?

@illia-v have you found a solution/workaround?

Is there a way to exclude properties / not directly queried fields?

**Comment by illia-v** [comment]
@blueyed I think a workaround was creating a method for the `foo` field
```python
@strawberry.django.type(Bar)
class BarType:
    @strawberry.field
    def foo(self, root: Bar) -> FooType:
        return root.get_foo()
```

**Comment by bellini666** [comment]
@blueyed @illia-v yes, defining a method resolver should work! Regarding the example, it would not work because `get_foo` is a function and not a property. If it was written like this it should work:

```python
class Foo(models.Model):
    pass


class Bar(models.Model): 
    @property   
    def get_foo(self) -> Foo:
        return Foo.objects.first()


@strawberry.django.type(Bar)
class BarType:
    get_foo: FooType = strawberry.field(name="foo")
```

**Comment by illia-v** [comment]
@bellini666 it does work if `get_foo` is a function, the breaking change of 0.8.2 was that it stopped working when `get_foo` was a function returning a model object. It started failing with that `argument 'pk' of type 'ID!' is required` error.

**Comment by bellini666** [comment]
> 

Oh sorry, I totally missed the previous messages (it is being a while).

Will try to take a look at the minimal reproduction example soon to try to fix it.

**Comment by bellini666** [comment]
Hey @illia-v @blueyed , sorry for taking so long to take a look at this.

Just opened a PR that should fix this issue.

**Comment by blueyed** [comment]
@bellini666 thank you! I can confirm that it fixes this issue.
