### ISSUE TITLE
A filter on a member's member doesn't work

### ISSUE THREAD

**Issue by shmoon-kr** [strawberry-graphql/strawberry-graphql-django#225]
`##` Describe the Bug

When I tried to add a filter of a member of a member of a django model, The filter was ignored without any error or warning.

Models are:

```
@strawberry_django.filters.filter(models.Store, lookups=True)
class StoreFilter:
    place_id: strawberry_django.filters.FilterLookup[strawberry.ID]
    place__zone_id: strawberry_django.filters.FilterLookup[strawberry.ID]
    zone_id: strawberry_django.filters.FilterLookup[strawberry.ID]


@strawberry.django.type(models.Store, filters=StoreFilter, pagination=True)
class Store:
    place: 'Place'
    zone: 'Zone'
    owner: 'User'


@strawberry.django.type(models.Place)
class Place:
    id: auto
    zone: 'Zone'


@strawberry.django.type(models.Zone)
class Zone:
    id: auto

```

Here, when I tried to filter Stores by zone_id, it works correctly.

```
variable:
{
    "filters": {
        "zoneId": {
            "exact": "1"
        }
    }
}
```
=> works correctly.

But when I tried to filter Stores by place__zone_id, it doesn't works correctly.

```
variable:
{
    "filters": {
        "place_ZoneId": {
            "exact": "1"
        }
    }
}
```
=> This filter is ignored and the query returns all data without applying filtering.

## System Information

 - Operating system: Ubuntu 20.04 LTS
 - Strawberry version (if applicable): strawberry-graphql-django~=0.8.2

**Comment by bellini666** [comment]
Hey @shmoon-kr ,

That is not supported currently. In this case you want to define nested filters:

```python
@strawberry_django.filters.filter(models.Zone, lookups=True)
class ZoneFilter:
    id: strawberry.auto


@strawberry_django.filters.filter(models.Place, lookups=True)
class PlaceFilter:
    id: strawberry.auto
    zone: ZoneFilter | None

@strawberry_django.filters.filter(models.Store, lookups=True)
class StoreFilter:
    place: ZoneFilter | None
```

Then you can reuse them and query like this:

```json
"place": {
  "id": {
    "exact": <place_id>
  },
  "zone": {
    "id": {
      "exact": <zone_id>
    }
  }
}
```

Note that I used `strawberry.auto` for simplification, but you can pass `strawberry_django.filters.FilterLookup[strawberry.ID]` as well

**Comment by shmoon-kr** [comment]
Thanks!
