### ISSUE TITLE
Field name of reversed relations

### ISSUE THREAD

**Issue by g-as** [strawberry-graphql/strawberry-graphql-django#24]
Hi,

django field name is used to determine the field name for the corresponding strawberry type.

This is obviously fine, but in the case of reversed relations, the `related_name` would be more appropriate IMO.

Something like that would do the trick:

```python

from django.db.models.fields.reverse_related import ForeignObjectRel

def get_model_fields(cls, model, fields, types, is_input, partial):

    [...]
    
    if isinstance(field, ForeignObjectRel)
        field_name = field.get_accessor_name()
    else:
        field_name = field.name

    model_fields.append((field_name, field_type, field_value))
```

I'll draft a PR tomorrow.

**Comment by la4de** [comment]
@g-as, thank you for feedback.

We are in the middle of publishing enhanced API where all fields would be defined class body as discussed in #20.

This internal function is refactored there and I definitely want to take this into account there.

**Comment by g-as** [comment]
A'ight, I'll go take a look.

**Comment by la4de** [comment]
This should work now with code in features/class-api branch. Feel free to try.

**Comment by g-as** [comment]
You rock!

**Comment by la4de** [comment]
See pull request #30
