### ISSUE TITLE
Tackling dynamic forms with Django strawberry

### ISSUE THREAD

**Issue by Mapiarz** [strawberry-graphql/strawberry-graphql-django#243]
Hi!

First of all, thanks for ongoing support for django strawberry, it's a great piece of software!

I have a question on how to handle dynamic form scenario in Django with Strawberry. The use case is this: We have a booking in our system to check in the customer, they need to fill out a form with a bunch of fields, such as agreeing to ToS, providing signature etc. Some fields on the form are dynamic and depend on the booking, so not every customer get's exactly the same form.

With Django + forms + views + html, it's pretty much a solved problem. I create a model so that I can persist the filled out form and then a Django form for it, with some fields being created dynamically. That form is serialized and client fills it out and then submits. If form is valid, the submission is saved as a Django object.

What are the possible options for me when working with GraphQL, strawberry django in particular? I'm new to GraphQL and am looking for guidance. I can't be the first person to face this issue :)

Futhermore, how can validation be performed that the user submitted the correct form (i.e. all required form fields that we first sent to the user have been filled out and that the form schema has not been modified)? What about form defaults? Forgery protection?

Any ideas and suggestions highly welcome.

**Comment by bellini666** [comment]
Hey @Mapiarz ,

Welcome to the GraphQL world :)

Regarding dynamic content, you can usually use [unions](https://strawberry.rocks/docs/types/union) for that.

But unfortunately the graphql spec doesn't support unions for [input types](https://strawberry.rocks/docs/types/input-types), which are the types that can be received in arguments.

Having said that, as long as the attributes in those inputs don't change type (e.g. `foo` can be a string or an int depending on the context), you can define those attributes as optional, meaning you are not required to provide them and you can even give them a default value, and validate the logic inside your [mutation resolver](https://strawberry.rocks/docs/general/mutations).

Btw, feel free to join our [discord server](https://strawberry.rocks/discord) and ask for help in your implementation if needed :)
