### ISSUE TITLE
Federation in for django type

### ISSUE THREAD

**Issue by firaskafri** [strawberry-graphql/strawberry-graphql-django#247]
## Feature Request Type

- [X] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Skimming through the code, I did not notice anything related to federation? is this feature available for django?

**Comment by patrick91** [comment]
hi @firaskafri, there's no built-in @strawberry.federation.django.type, but you can add the directives manually (that's what the strawberry decorator does after all :))

See: https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/federation/object_type.py#L53-L68

**Comment by firaskafri** [comment]
> hi @firaskafri, there's no built-in @strawberry.federation.django.type, but you can add the directives manually (that's what the strawberry decorator does after all :))
> 
> See: https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/federation/object_type.py#L53-L68

neat!
