### ISSUE TITLE
relay: problems with _id and _id_attr

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry-graphql-django#258]
The novel relay approach causes the  _id and _id_attr to appear in strawberry-graphql-django

The problem is the get_fields function which doesn't filter fields as dataclass.fields do.

It would be maybe better to use the same approach as in strawberry as it caused already some problems with Private

**Comment by bellini666** [comment]
I'm currently adjusting that for strawberry-django-plus (not only to fix that but also to use the new relay infrastructure instead of its own implementation) and will update this to use the same solution :)

**Comment by devkral** [comment]
finished the PR ;). Now it should work

**Comment by bellini666** [comment]
Closing this as fixed on strawberry core
