### ISSUE TITLE
relay depth limit

### ISSUE THREAD

**Issue by tasiotas** [strawberry-graphql/strawberry-graphql-django#261]
Hi,

I was reading [blog](https://blog.cloudflare.com/protecting-graphql-apis-from-malicious-queries/) from Cloudflare about malicious queries in GraphQL.

Is there a way to detect query depth so I can respond respectively ?

```gql
query {
 petition(ID: 123) {
   signers {
     nodes {
       petitions {
         nodes {
           signers {
             nodes {
               petitions {
                 nodes {
                    ...
                 }
               }
             }
           }
         }
       }
     }
   }
 }
}
```

Thanks

**Comment by bellini666** [comment]
Hey @tasiotas ,

You can probably use the [QueryDepthLimiter](https://strawberry.rocks/docs/extensions/query-depth-limiter) for this :)

**Comment by tasiotas** [comment]
ah, perfect. I missed that one while checking docs.

thanks

**Comment by tasiotas** [comment]
How can I return specific response code (400) instead of 200 when validator fails?

Currently it responds with 200 and this message.

```gql
{
  "data": null,
  "errors": [
    {
      "message": "'MyQuery' exceeds maximum operation depth of 2",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ]
    }
  ]
}
```

**Comment by bellini666** [comment]
@tasiotas that's basically how graphql works. Unlike rest, where the response code tells you if the query worked or not, the presence of `errors` indicates a "500"

You can force a 4xx/5xx in the django view by overriding it and changing its response status_code to 4xx/5xx based on the presence of an `errors`. You can do that by overriding [this method](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/django/views.py#L158) in the view

**Comment by tasiotas** [comment]
perfect, thanks again!

here is my solution, not sure if I overridden it correctly, but it seems to be working 🚀

```python
#urls.py

class MyGraphQlView(GraphQLView):
    def create_response(
        self, response_data: GraphQLHTTPResponse, sub_response: HttpResponse, *args, **kwargs
    ) -> HttpResponse:
        if "errors" in response_data:
            sub_response.status_code = status.HTTP_400_BAD_REQUEST

        # return response
        return super(MyGraphQlView, self).create_response(
            response_data=response_data, sub_response=sub_response, *args, **kwargs
        )

urlpatterns = [
    path(settings.ADMIN_URL + "api/graphiql", MyGraphQlView.as_view(schema=schema)),
]
```
