### ISSUE TITLE
missing: management command for exporting schema

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry-graphql-django#280]
one small thing which is missing is the schema export of strawberry-django-plus

It would be nice to have it here as it is really useful.

**Comment by djstein** [comment]
hey @devkral here is the generate schema code from my project, you might be able to add a PR super quick:


dir structure: 
```
strawberry_django/
- management/
- __init__.py
-- commands/
-- __init__.py
-- generate_schema.py
```

generate_schema.py contents
```python
from django.core.management import BaseCommand
from strawberry.printer import print_schema

from graphql_api.schema import schema


class Command(BaseCommand):
    help = "Exports the Strawberry GraphQL schema"

    def handle(self, *args, **options):
        with open("schema.gql", "w") as f:
            f.write(print_schema(schema))

```

**Comment by bellini666** [comment]
Hey @devkral ,

Indeed! The reason I didn't port it was because there is an open PR from @menegasse contributind that directly to strawberry: https://github.com/strawberry-graphql/strawberry/pull/2571

@patrick91 do you think that code is ok to be merged?

**Comment by devkral** [comment]
or simply copying the strawberry-django-plus command code ;)
