### ISSUE TITLE
0.10.x stopped passing filters to `get_queryset` of types

### ISSUE THREAD

**Issue by illia-v** [strawberry-graphql/strawberry-graphql-django#294]
0.9.5 and previous versions [used to pass](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/7ee0a7c8e55a27eb88bc26d31316b62061447063/strawberry_django/fields/field.py#L158C13-L158C62) filters as an item of `kwargs` to `get_queryset` of types.

0.10.x [stopped](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/01b8abe7a1892519f476b4a56408333ad65c3f40/strawberry_django/fields/field.py#L255C24-L256C1) doing so contradicting [this piece of documentation](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/01b8abe7a1892519f476b4a56408333ad65c3f40/docs/guide/types.md?plain=1#L122-L123)

**Comment by bellini666** [comment]
Hi @illia-v ,

Thanks for pointing that out, I might have changed it by mistake during the whole refactoring that I did in the lib.

I'll try to fix this during the weekend!

**Comment by bellini666** [comment]
I actually already created a fix for this! :)

**Comment by illia-v** [comment]
Hi @bellini666,

Thanks for the quick fix!
