### ISSUE TITLE
Regression/question on strawberry_django.filter

### ISSUE THREAD

**Issue by g-as** [strawberry-graphql/strawberry-graphql-django#298]
When providing a custom type for filter fields, the `filter` decorator used to (in v0.9.x) set all fields optional, but not anymore.

From the documentation:
```
@strawberry.django.filter(models.Fruit)
class FruitFilter:
    id: auto
    name: auto
    color: "ColorFilter"

@strawberry.django.filter(models.Color)
class ColorFilter:
    id: auto
    name: auto
```
now produces:
```
input ColorFilter {
  id: ID
  name: String
}

input FruitFilter {
  id: ID
  name: String
  color: ColorFilter!
}
```
and not
```
input FruitFilter {
  id: ID
  name: String
  color: ColorFilter
}
```
Is this the desired behaviour?

**Comment by bellini666** [comment]
Hi @g-as ,

Yes, this is in fact an API change that I totally forgot to document.

In that case, `auto` fields will still be forced to be optional, but non auto fields must be typed properly. This was "too magical" and usually confused users (even myself)

To fix that what you can do is `color: "ColorFilter | None" = UNSET`.
Maybe I should update the docs to explain that

**Comment by bellini666** [comment]
> I was indeed confused by the documentation.

Can you point out what got you confused, so I can try to improve it?

Also, feel free to open a PR to improve it. The documentation needs a lot of love currently =P
