### ISSUE TITLE
Strawberry types don't pick up fields from parent classes

### ISSUE THREAD

**Issue by Mapiarz** [strawberry-graphql/strawberry-graphql-django#301]
## Describe the Bug

Consider this schema:

```python
class MyCommonStuff:
    foo: strawberry.auto
    bar: strawberry.auto

@strawberry_django.type(models.MyModel)
class MyModelState(MyCommonStuff):
    baz: strawberry.auto

@strawberry_django.partial(models.MyModel)
class MyModelStateInputPartial(MyCommonStuff):
    qwe: strawberry.auto
```

In the generated graphql schema `MyModelState` will only have field `baz` (incorrect) whereas `MyModelStateInputPartial` will have all `foo`, `bar` and `qwe` (correct). 

This can be worked around by adding a `@dataclass` annotation to `MyCommonStuff`.

## System Information

 - Strawberry version (if applicable): 0.11.0

**Comment by bellini666** [comment]
Hi @Mapiarz ,

This is actually how it works even for dataclasses. If you have a dataclass inheriting from another class with annotations, those will only be considered fields if that parent class is a dataclass itself as well.

The workaround of adding an `@dataclass` or even an `@strawberry.type` is actually the proper way of doing that :)

**Comment by bellini666** [comment]
You can see here that either `Bar` and `Bin` doesn't have a `foo` field

```python
In [1]: import dataclasses

In [2]: class Foo:
   ...:     foo: str
   ...: 

In [5]: @dataclasses.dataclass
   ...: class Bar(Foo):
   ...:     bar: str
   ...: 

In [6]: dataclasses.fields(Bar)
Out[6]: (Field(name='bar',type=<class 'str'>,default=<dataclasses._MISSING_TYPE object at 0x7f73546760d0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f73546760d0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD),)

In [7]: @dataclasses.dataclass
   ...: class Bin(Bar):
   ...:     bin: str
   ...: 

In [8]: dataclasses.fields(Bin)
Out[8]: 
(Field(name='bar',type=<class 'str'>,default=<dataclasses._MISSING_TYPE object at 0x7f73546760d0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f73546760d0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD),
 Field(name='bin',type=<class 'str'>,default=<dataclasses._MISSING_TYPE object at 0x7f73546760d0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f73546760d0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD))
```

**Comment by kwongtn** [comment]
Was going to post this too, cause I've been using such a pattern with `strawberry_django_plus` and things start breaking 😂 
And yes adding the `@dataclass` decorator works 😁 

Probably will need to add in docs later on

**Comment by Mapiarz** [comment]
Thanks for this clarification @bellini666 ! Nonetheless, keep in mind that partial type still picked up the base class fields without `@dataclass` annotation ;) Something's funky.

**Comment by bellini666** [comment]
@Mapiarz oh really? D:

That should not happen! Thanks for pointing it out, will take a look at that soon
