### ISSUE TITLE
Authentication: misleading returns and errors

### ISSUE THREAD

**Issue by 2malh** [strawberry-graphql/strawberry-graphql-django#31]
While authentication is only implemented on a very basic level with login() and logout() for now I think the feedback send to the user could be a little clearer on what's going on. Here are some examples of what's currently being returned:

```graphql
"""
login with false credentials
"""
mutation Login {
  login(username: "test@user.com", password: "wrongpassword") {
    username
  }
}

"""
username only returns as an empty string.
Here I'm somewhat missing an UserNotFoundError.
How could this be implemented?
"""
{
  "data": {
    "login": {
      "username": ""
    }
  }
}
```
```graphql
"""
login with false credentials and querying for any other
field than username (which is provided as input)
"""
mutation Login {
  login(username: "test@user.com", password: "wrongpassword") {
    uuid
    username
  }
}

"""
because no user is found the query is broken.
Instead it should be a UserNotFoundError and
the requested fields set to null or not?
"""
{
  "data": null,
  "errors": [
    {
      "message": "'AnonymousUser' object has no attribute 'uuid'",
      "locations": [
        {
          "line": 27,
          "column": 5
        }
      ],
      "path": [
        "login",
        "uuid"
      ]
    }
  ]
}
```
```graphql
"""
calling logout without being logged in
"""

mutation Logout {
  logout
}

"""
I don't know if this is correct of if it should rather add
a note that the user hasn't been logged in before?
"""
{
  "data": {
    "logout": true
  }
}

```

I think it'd also be very useful to implement the new ExecutionContext from strawberry to easily check if there have been errors during the execution. Especially for the mentioned login mutations. Is this hard to implement?

What do you think?
As always: TThanks so much for all your work! <3

**Comment by la4de** [comment]
I changed `login` mutation so that it returns user in case of success and null if login fails. `logout` mutation returns true if user was logged in and false if there was not user.

`auth.current_user()` returns user or null.

Are you happy with these changes?

We can discuss about execution context but I'd say that it would be good to have separate ticket for that.

**Comment by la4de** [comment]
Please reopen the ticket if you are not happy with the solution.
