### ISSUE TITLE
Make m2m through table fields available

### ISSUE THREAD

**Issue by 2malh** [strawberry-graphql/strawberry-graphql-django#32]
To quote @adamcharnock who was/is suggesting the same for [graphene-django](https://github.com/graphql-python/graphene/issues/83#issue-127473108)
> When a `DjangoConnectionField` traverses a many-to-many field it would be nice to have the option to expose the fields of any through-table on the edges of the relationship.

In the following scenario:
```py
@strawberry_django.type(Projeect)
class Project:
  name: auto
  members: List[User]

@strawberry_django.type(User)
class User:
  username: auto

# this is the intermediate m2m through table
@strawberry_django.type(Project_Membership)
class Project_Membership:
  project: 'Project'
  user: 'User'
  additional_field_1: auto
  additional_field_2: auto
  is_admin: auto
  can_edit: auto
```

out of the box this resolves quit well:
```gql
query ProjctMembers {
  projects {
    name
    members {
      username
    }
  }
}
```
however it's not yet possible to access the additional fields of the Project_Membership table. Exposing these fields to the api can be essential in a lot of ways.

**Comment by la4de** [comment]
I pushed fix for relation field name resolution which should enable your use case. See `test_m2m_through.py` test. Please update to v0.2.1 and let us know if it works for you.

Following should work now:
```python
@strawberry_django.type(models.Project_Membership)
class Project_Membership:
  project: 'Project'
  user: 'User'

@strawberry_django.type(models.Project)
class Project:
    name: auto
    membership: List[Project_Membership] = strawberry_django.field(field_name='project_membership_set')

@strawberry_django.type(models.User)
class User:
    username: auto
    membership: List[Project_Membership] = strawberry_django.field(field_name='project_membership_set')
```

See https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/tests/queries/test_m2m_through.py
