### ISSUE TITLE
Reverse relationship query not working in particular situations

### ISSUE THREAD

**Issue by ryanprobus** [strawberry-graphql/strawberry-graphql-django#324]
## Describe the Bug
Difference in behavior when a field is resolved via `strawberry_django.auth.current_user()` vs. `strawberry_django.node()` related to async.

## System Information
 - Async
 - Docker image base: `python:3.11-slim-bookworm`
 - Strawberry version: `0.196.2` 
 - Strawberry GraphQL Django version: `0.14.1`
 - Strawberry Django Auth version: `0.375.0`

## Additional Context
Representative Example:
```
class FollowRelationship(Model):
  from_user = models.ForeignKey(
    to="User",
    null=False,
    blank=False,
    related_name="following",
    on_delete=models.CASCADE,
  )
  to_user = models.ForeignKey(
    to="User",
    null=False,
    blank=False,
    related_name="followers",
    on_delete=models.CASCADE,
  )
  ...

class User(AbstractUser):
  ...

@strawberry_django.type(FollowRelationship)
class FollowRelationshipType(strawberry.relay.Node):
  from_user: "UserType"
  to_user: "UserType"
  ...

@strawberry_django.type(User)
class UserType(strawberry.relay.Node):
  followers: strawberry_django.relay.ListConnectionWithTotalCount[FollowRelationshipType] = strawberry_django.connection()
  ...

@strawberry.type
class Query:
  user: UserType = strawberry_django.node()
  current_user: Optional[UserType] = strawberry_django.auth.current_user()
```

When I issue a query:
```
query {
  currentUser {
    followers {
      ...
    }
  }
  user(id: "<current-user-id>") {
    followers {
      ...
    }
  }
}
```

The `currentUser` query fails due to:
```
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
                                        ^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/strawberry_django/fields/field.py", line 361, in async_resolver
    resolved = await resolved
                ^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/strawberry_django/relay.py", line 103, in wrapper
    resolved = await conn
               ^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/strawberry/relay/types.py", line 874, in resolver
    assert isinstance(iterator, (AsyncIterator, AsyncIterable))
```
whereas the `user` query works. I can query most other fields on `currentUser` the same as through `user`  except reverse relationships. I was able to assert that the `current_user` resolver I provided was returning a `User` class object of the currently authenticated user (not anonymous user). Please let me know if there's any additional information I can provide or if you have any other recommendations.

**Comment by bellini666** [comment]
What version of django are you using?

Based on the error, it seems that either the nodes iterable that the connection tried to resolve was not a queryset (since it should be an instance of `AsyncIterable`), or you are using an older version of django which didn't have async iteration over the queryset.

**Comment by ryanprobus** [comment]
@bellini666 Hi, thanks for your attention again. I really appreciate it. You have helped me before in the Discord channel as well. I am currently on django `4.2.3`. It looks like the newest stable version is `4.2.4`, but the [release notes](https://docs.djangoproject.com/en/4.2/releases/4.2.4/) for that patch don't mention anything about async iteratators.

```
>>> django.VERSION
(4, 2, 3, 'final', 0)
```

However, something does seem to be up WRT `QuerySet` (django.db.models) not implementing AsyncIterable. When I was migrating, I was following the docs and for connections that I define the resolver, I was trying to set the return type to `QuerySet[SomeDjangoType]` but get this error:
```
error: Wrong annotation used on `<field-name>` resolver. It should be return  
an `iterable` or `async iterable` object.
```
I have had to set those return types to `Iterable[SomeDjangoType]` instead.

Is there a particular django version you would recommend or would you expect this django version to work?

**Comment by bellini666** [comment]
> Hi, thanks for your attention again. I really appreciate it. You have helped me before in the Discord channel as well

Happy to be helpful :)

Regarding the typing issue, the you can actually type the resolver return value as `Iterable`. e.g.

```python
@strawberry.type
class Query:
    @strawberry_django.connection(ListConnectionWithTotalCount[SomeModelType])
    def some_conn(self) -> Iterable[SomeModel]:
        return SomeModel.objects.all()
```

As long as your django is properly typed (I recomend using [this stubs lib](https://github.com/sbdchd/django-types)), that will not produce any issues with pyright/mypy and will work with the connection implementation.

> Played in shell and it seems like QuerySet is a AsyncIterable and AsyncIterator even though when I try to type hint that as the return type of a connection resolver it doesn't like it.

Indeed, that's why I asked your django version. On django QuerySet's versions didn't have an `__aiter__` method, meaning they could not be asynchronously iterated. That's also the reason why we have [this workaround](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/strawberry_django/relay.py#L77) for django 4.1 or older.

The fact that the assertion is failing there, even though you are using django 4.2+, means the connection is not receiving a queryset to work with there. Could you check what it is? Also, is that traceback from that exact piece of code you shared or do you have any kind of custom resolvers in there?

**Comment by ryanprobus** [comment]
@bellini666 

> As long as your django is properly typed (I recomend using [this stubs lib](https://github.com/sbdchd/django-types)), that will not produce any issues with pyright/mypy and will work with the connection implementation.

Thanks, I didn't know about this alternative to `django-stubs`. I will try it out.

> The fact that the assertion is failing there, even though you are using django 4.1+, means the connection is not receiving a queryset to work with there. Could you check what it is? Also, is that traceback from that exact piece of code you shared or do you have any kind of custom resolvers in there?

The type is a list. This list contains two `FollowRelationship` django models. I have no custom resolvers in there. The example code is what I believed is the entirety of relevant code from within my codebase. I have omitted other models, gql types and gql fields. However, when I tried to create an entirely minimal reproduction, I was unsuccessful despite setting almost everything up the same as my main project. In the reproduction it seemed to consistently work. :sweat:

**Comment by bellini666** [comment]
> However, when I tried to create an entirely minimal reproduction project, I was unsuccessful despite setting almost everything up the same as my main project. In the reproduction it seemed to consistently work. sweat

Ohh T_T

Taking a look at this again, I think it has something to do with the queryset being already prefetched and returning a list when sliced. If my assumption is correct, [this strawberry PR](https://github.com/strawberry-graphql/strawberry/pull/3014) should fix the issue

**Comment by ryanprobus** [comment]
@bellini666 That looks like it would fix what I'm running into! Thanks for taking the time to look into this. Feel free to close this issue at your preference. As I become more familiar with async and this library, I'll try to come with solutions instead of problems =).

**Comment by bellini666** [comment]
> @bellini666 That looks like it would fix what I'm running into! Thanks for taking the time to look into this. Feel free to close this issue at your preference. As I become more familiar with async and this library, I'll try to come with solutions instead of problems =).

Hahaha, reporting issues is always helpful as well :)

Going to close this since the fix was released on strawberry during the weekend
