### ISSUE TITLE
Interfaces cannot inherit Strawberry Django Types that use `auto`

### ISSUE THREAD

**Issue by fireteam99** [strawberry-graphql/strawberry-graphql-django#327]
## Describe the Bug
Trying to inherit a Strawberry Django Type that uses `auto` in an interface causes an `Unexpected type 'typing.Any'` error.

For example:
```py
@strawberry.django.type(MyModel):
class MyModelNode():
    foo: auto

@strawberry.interface
class MyInterface(MyModelNode):
    bar: str
```

Throws the following error:
```
app_1  |   File "/code/backend_service/medallion/api_graphql/schema.py", line 101, in <module>
app_1  |     schema = strawberry.Schema(
app_1  |   File "/usr/local/lib/python3.9/site-packages/strawberry/schema/schema.py", line 141, in __init__
app_1  |     self._schema = GraphQLSchema(
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/schema.py", line 224, in __init__
app_1  |     collect_referenced_types(query)
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/schema.py", line 433, in collect_referenced_types
app_1  |     collect_referenced_types(field.type)
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/schema.py", line 433, in collect_referenced_types
app_1  |     collect_referenced_types(field.type)
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/schema.py", line 424, in collect_referenced_types
app_1  |     collect_referenced_types(member_type)
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/schema.py", line 430, in collect_referenced_types
app_1  |     collect_referenced_types(interface_type)
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/schema.py", line 432, in collect_referenced_types
app_1  |     for field in named_type.fields.values():
app_1  |   File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
app_1  |     val = self.func(instance)
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/type/definition.py", line 945, in fields
app_1  |     raise cls(f"{self.name} fields cannot be resolved. {error}") from error
app_1  | TypeError: MyInterface fields cannot be resolved. Unexpected type 'typing.Any'
```

## System Information

 - Operating system: macOS
 - Strawberry version (if applicable): strawberry-graphql `0.199.2`, strawberry-graphql-django `0.16.0`

## Additional Context
Attempting to use the new `fields="__all__"` feature results in the same error described above. Example:
```py
@strawberry.interface
class MyInterface(MyModelNode, fields="__all__"):
    ...
```

This bug was not present in previous versions. Specifically, it was working as expected in: strawberry-graphql `0.133.5`, strawberry-graphql-django `0.7`

**Comment by bellini666** [comment]
Hi @fireteam99 ,

Hrm, interesting use case. I personally have a lot of mixin models which I use `@strawberry_django.interface(MyMixinModel)` and use those in my django types, which usually implement those mixins. This is the first time I see the other way around happening (an interface inheriting from a type).

I'll try to take a look on what caused the regression. But for curiosity, what is you use case for making an interface inherit from a type? Because it is usually the other way around

**Comment by fireteam99** [comment]
Hey @bellini666, it's because I am dealing with an abstract model in Django. Specifically I have: 

```
Model A (concrete) --> Model B (abstract) --> Model C (concrete)
```

Therefore, I have to represent Model B as an interface which inherits from Model A (a type).

**Comment by bellini666** [comment]
Hey @fireteam99 ,

I just tested here and I was able to define a strawberry_django interface which inherits from a strawberry_django type. No issues.

Do you have a minimal reproduction example for that?

**Comment by fireteam99** [comment]
@bellini666 did your base model use the `auto` keyword? Regardless, I will try to replicate in a clean environment!

**Comment by bellini666** [comment]
> @bellini666 did your base model use the `auto` keyword? Regardless, I will try to replicate in a clean environment!

Yes it did =P

Waiting for the replication :)

**Comment by fireteam99** [comment]
Sorry for the delay, I was able to reproduce the issue on a clean environment. It looks like the error doesn't manifest until expose type that inherits from the interface (which inherits from a node that uses `auto`) in the schema.

```py
# person/models.py

from django.db import models

class Person(models.Model):
    title = models.CharField(max_length=255)
    age = models.IntegerField()
    birthday = models.DateField()

class Employee(Person):
    class Meta:
        abstract = True

    salary = models.FloatField()
    company = models.CharField(max_length=255)

class Admin(Employee):
    access_code = models.CharField(max_length=255)

```

```py
# schema.py

import strawberry
from person import models
from strawberry.tools import merge_types
from strawberry import auto

@strawberry.django.type(model=models.Person)
class Person:
    title: auto
    age: auto
    birthday: auto

@strawberry.interface
class EmployeeInterface(Person):
    salary: float
    company: str

@strawberry.django.type(model=models.Admin)
class Admin(EmployeeInterface):
    access_code: auto

@strawberry.type(name="Query")
class PersonQuery:
    person: Person = strawberry.django.field()
    people: list[Person] = strawberry.django.field()

    admin: Admin = strawberry.django.field()
    admins: list[Admin] = strawberry.django.field()


Query = merge_types(
    "Query",
    (
        PersonQuery,
    ),
)

schema = strawberry.Schema(query=Query)
```

Results in the following error:
```
  File "/Users/ray/Library/Caches/pypoetry/virtualenvs/strawberry-django-playground-M3f0DcHo-py3.11/lib/python3.11/site-packages/graphql/type/definition.py", line 945, in fields
    raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: EmployeeInterface fields cannot be resolved. Unexpected type 'typing.Any'
```

Updating `Person` to not use `auto` fixes the error:
```py
class Person:
    title: str
    age: int
    birthday: datetime
```

**Comment by bellini666** [comment]
Hi @fireteam99 ,

In your example, the issue there is that you are mixing strawberry django fields with strawberry fields.

More specifically, you are using `@strawberry.interface` in a class that inherits from a `@strawberry.django.type` class. strawberry itself doesn't have the same code that handles `auto` and that leads to the issue you are seeing there.

What you want to do in that case is to use `@strawberry.django.interface(model=models.Person)`. I tested here and it should fix your issue!

Please tell me if that is enough for us to close this or if there's any corner case I'm not considering here

**Comment by fireteam99** [comment]
Hey @bellini666 sorry I missed your response until now. Can confirm that using the `@strawberry.django.interface` decorator fixes the problem! Thanks for investigating!
