### ISSUE TITLE
How to locate model on uuid instead of id ?

### ISSUE THREAD

**Issue by ldynia** [strawberry-graphql/strawberry-graphql-django#348]
The default CUD operation in srawberry_django identifies the model to be mutated by the model's id (the database's id column, which is the Primary Key). How can I change this behavior to point to a column's/model's UUID without overriding strawberry_django.mutations.update method?

In simple terms, how to do a search on a field that is not id/PK in [strawberry-graphql-djang](https://github.com/strawberry-graphql/strawberry-graphql-django) without mending update method?

**Comment by ldynia** [comment]
Hi @bellini666
I'd love to do PR, but I have no time for it :(. If someone is interested in implementing this, then I drop this [answer on stackoverflow.com](https://stackoverflow.com/questions/76980047/how-to-resolve-models-in-cud-operations-not-on-pk-but-on-uuid). It's a good place to pick it up.

**Comment by thepapermen** [comment]
@bellini666, @ldynia, so just for fun I have made the PR which adds this feature.

**Comment by ldynia** [comment]
:heart: it! I'll test it once it's merged. But at the moment PR is stopped by this error: https://github.com/strawberry-graphql/strawberry-graphql-django/pull/387

**Comment by bellini666** [comment]
@thepapermen just reviewed your PR :)

There are a couple of minor comments there that after fixed should be good to be merged

**Comment by thepapermen** [comment]
> ❤️ it! I'll test it once it's merged. But at the moment PR is stopped by this error: #387

@ldynia, now it's merged. :smile:

**Comment by ldynia** [comment]
@bellini666 I finally found time to test it. It works like a charm :)

Live long and Pull Request!
