### ISSUE TITLE
Namespace "strawberry.django" removed type hinting support in VS Code

### ISSUE THREAD

**Issue by 2malh** [strawberry-graphql/strawberry-graphql-django#35]
With the change of the namespace from `strawberry_django` to `strawberry.django` it removed VS Codes Intellisense type hinting support for Strawberry.

Before:
![grafik](https://user-images.githubusercontent.com/42282368/120376555-535c7180-c31c-11eb-96d2-ff066af9f713.png)

After:
![grafik](https://user-images.githubusercontent.com/42282368/120376507-4475bf00-c31c-11eb-813b-dad6298c0cfc.png)

This was very handy because one could just right click and jump to the definition for types e.g. This is not possible anymore. Now everything is `Any`.

Before:
![grafik](https://user-images.githubusercontent.com/42282368/120376826-9dddee00-c31c-11eb-98a8-a9643273cbe2.png)

After:
![grafik](https://user-images.githubusercontent.com/42282368/120376969-c9f96f00-c31c-11eb-92fa-ca61d405b20b.png)

**Comment by la4de** [comment]
Proposal for fix: https://github.com/strawberry-graphql/strawberry/pull/994

**Comment by la4de** [comment]
Fix pushed to strawberry core. Please update to the strawberry-graphql package.

**Comment by la4de** [comment]
Fix introduced regression. See #36.

**Comment by la4de** [comment]
This can be get working by adding `import strawberry.django` to the code. That's the best solution we have just now. Documented to README.md file:
https://github.com/strawberry-graphql/strawberry-graphql-django#autocompletion-with-editors
