### ISSUE TITLE
Import error in example from README.md

### ISSUE THREAD

**Issue by NeoLight1010** [strawberry-graphql/strawberry-graphql-django#36]
When trying to create a type similar to the example in README.md, an error occurs:

![imagen](https://user-images.githubusercontent.com/58057324/120525607-ebe70600-c39d-11eb-8282-2a89eafff1e4.png)

This is the example in README.md:

![imagen](https://user-images.githubusercontent.com/58057324/120525650-fb664f00-c39d-11eb-8903-741cf2bc7a81.png)

The error can be solved by changing `import strawberry` to `import strawberry.django`, so I think README.md should be changed:

![imagen](https://user-images.githubusercontent.com/58057324/120525755-19cc4a80-c39e-11eb-827c-df31054f593d.png)

**Comment by la4de** [comment]
Proposal for fix: https://github.com/strawberry-graphql/strawberry/pull/994

**Comment by la4de** [comment]
Fix pushed to strawberry core. Please update the strawberry-graphql package.

**Comment by la4de** [comment]
The fix introduced new circular import issue. Fix will be reverted. We need to find out another solution.

**Comment by la4de** [comment]
Workaround to get autocompletion working is to add
```python
import strawberry.django
```
to your code as @NeoLight1010 already mentioned.

**Comment by la4de** [comment]
This is now documented in README.md file:
https://github.com/strawberry-graphql/strawberry-graphql-django#autocompletion-with-editors
