### ISSUE TITLE
GlobalID not returned via query

### ISSUE THREAD

**Issue by sdobbelaere** [strawberry-graphql/strawberry-graphql-django#372]
I've setup Strawberry django for a Company model, and created types, input types, queries via relay and mutations.
Also, I've setup the `MAP_AUTO_ID_AS_GLOBAL_ID: True` setting.

When I look at the query result, I can see that the object ID is mapped as a GlobalID.
<img width="1304" alt="Screenshot 2023-09-21 at 16 32 48" src="https://github.com/strawberry-graphql/strawberry-graphql-django/assets/16462709/8571de91-9489-4046-8470-48efdbd6a814">

However, when I want to try and remove that object, the mutation is complaining that my ID is of the wrong type and should be a base64 string.  
<img width="1318" alt="Screenshot 2023-09-21 at 16 33 19" src="https://github.com/strawberry-graphql/strawberry-graphql-django/assets/16462709/e1f62e61-8b60-4abb-98f3-f40f79859c4c">

If the mutation is correct, shouldn't the query supply me with an actual converted GlobalID instead of a stringified id?
Or perhaps I'm missing something in my setup?

Some more detail on the models, types, inputtypes and queries below:

```python
class Company(models.Model):
    name = models.CharField(max_length=100)

@strawberry.django.type(Company, filters=CompanyFilter, order=CompanyOrder, pagination=True, fields='__all__')
class CompanyType(relay.Node):
    pass

@strawberry_django.input(Company)
class CompanyInput:
    id: auto
    name: auto

@strawberry.type(name="Query")
class ContactsQuery:
    company: CompanyType = strawberry_django.field(extensions=[IsAuthenticated()])
    companies: ListConnectionWithTotalCount[CompanyType] = strawberry_django.connection(extensions=[IsAuthenticated()])


@strawberry.type(name="Mutation")
class ContactsMutation:
    create_company: CompanyType = mutations.create(CompanyInput, extensions=[IsAuthenticated()])
    create_companies: List[CompanyType] = mutations.create(CompanyInput, extensions=[IsAuthenticated()])
    update_company: List[CompanyType] = mutations.update(CompanyPartialInput, extensions=[IsAuthenticated()])
    delete_company: CompanyType = mutations.delete(NodeInput, extensions=[IsAuthenticated()])
    delete_companies: List[CompanyType] = mutations.delete(NodeInput, extensions=[IsAuthenticated()])

```

**Comment by bellini666** [comment]
Hi @sdobbelaere ,

Hrm, that is a corner case of the `fields='__all__'` you are using.

I'll try to take a look at that soon

**Comment by sdobbelaere** [comment]
Interesting @bellini666, what should I be seeing?

The following stripped down type, with manually declared fields yields the same query response:

```python
@strawberry.django.type(Company)
class CompanyType(relay.Node):
    id: auto
    name: auto
    related_companies: List['CompanyType']


@strawberry.type(name="Query")
class ContactsQuery:
    companies: ListConnectionWithTotalCount[CompanyType] = strawberry_django.connection(extensions=[IsAuthenticated()])

``` 

```graphql
{
  companies(first:1) {
    edges {
      node {
        name
        id
      }
    }
  }
}

``` 
```json
{
  "data": {
    "companies": {
      "edges": [
        {
          "node": {
            "name": "Some name",
            "id": "1"
          }
        }
      ]
    }
  }
}
```

**Comment by sdobbelaere** [comment]
Oh I see, it's the declaring of field `id` that causes the original id to be shown instead of the hash.

As a workaround, it seems that excluding the id from the fields returns the right data.
```python
@strawberry_django.type(Company, filters=CompanyFilter, order=CompanyOrder, pagination=True, exclude=['id'])
class CompanyType(relay.Node, TypeMultiTenantFilterMixin):
    name: auto
    related_companies: List['CompanyType']
```

```graphql
{
  companies(first:1) {
    edges {
      node {
        name
        id
      }
    }
  }
}
```

```json
{
  "data": {
    "companies": {
      "edges": [
        {
          "node": {
            "name": "Some Name",
            "id": "Q29tcGFueVR5cGU6MQ=="
          }
        }
      ]
    }
  }
}
```

**Comment by sdobbelaere** [comment]
@bellini666 I added a pull-request to exclude the id from the model-fields.  This seemed to be the lowest hanging fruit to handle the inclusions.  Looking forward to your thoughts.
