### ISSUE TITLE
circular import with m2m fields

### ISSUE THREAD

**Issue by sky-code** [strawberry-graphql/strawberry-graphql-django#39]
How to solve problem with m2m fields and circular import? is there any way for "lazy" type declaration?

**Comment by la4de** [comment]
Thanks for your question.

Yes, Strawberry core has LazyType. See cyclic test: https://github.com/strawberry-graphql/strawberry/tree/main/tests/test_cyclic

Hopefully this answers to your question.

**Comment by la4de** [comment]
I'll close this now. Feel free to reopen it if you have any further questions.
