### ISSUE TITLE
Returning dict with a datetime isn't compatible with JSON type

### ISSUE THREAD

**Issue by noamsto** [strawberry-graphql/strawberry-graphql-django#429]
## Describe the Bug

I have a resolver which  need to return dictionaries which are not per-defined (read from a DB) 
Therefore I use `list[JSON]` type.
i.e.: 

```python
from strawberry.scalars import JSON

@strawberry.type
class QueryData:
    rows:  list[JSON] | None

```

For input like this:

```python
[{'store_id': 1,
  'manager_staff_id': 1,
  'address_id': 1,
  'last_update': datetime.datetime(2006, 2, 15, 9, 57, 12)}]
```

I get the above TypeError:
`TypeError: Object of type datetime is not JSON serializable`

my resolver for reference:

```python
    @strawberry.field
    def execute_query(self, sql_query: str) -> types.QueryData:
        rows = execute(sql_query)
        return types.QueryData(rows=rows)
```

## System Information

 - Operating system: Nixos
 - Strawberry version (if applicable):

## Additional Context

 Changing the json_encoder class to DjangoJSONEncoder can solve the issue.
 
 It looks like it was done for the other integrations
 strawberry-graphql/strawberry#2272

**Comment by bellini666** [comment]
Hi @noamsto ,

I think this makes sense!
Do you want to try to open a PR for it? You probably want to override the [encode_json method](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/django/views.py#L162) in the django view.

**Comment by noamsto** [comment]
I have created a PR in Strawberry project: https://github.com/strawberry-graphql/strawberry/pull/3273
If it won't be accepted for some reason, I suggest extend the BaseView in this project maybe?
but I don't see a reason they won't accept it.
