### ISSUE TITLE
Execution context of field extensions attached to CUD mutation is always sync 

### ISSUE THREAD

**Issue by m4riok** [strawberry-graphql/strawberry-graphql-django#433]
Hello @bellini666 

When running under `asgi` and with an async graphql view, attaching field extensions that implement `resolve_async`  to CUD mutations always leads to the extensions `resolve` being called instead of `resolve_async`. 

I had previously opened this [issue](https://github.com/strawberry-graphql/strawberry/issues/3236)  with strawberry that outlines what the problem is and was advised to re-open this issue on this repository. 

## Describe the Bug

This issue occurs due to the wrapping of resolver functions with `@sync_to_async`  which will not be recognized by strawberry's `field.is_async`  and field extensions sync resolvers will be pushed into the chain instead during schema conversion.  This happens because: 

1.  `base_resolver` of CUD mutations evaluate to None during schema conversion 
```python
@cached_property
    def is_async(self) -> bool:
        return self._has_async_permission_classes or self._has_async_base_resolver
@property
    def _has_async_base_resolver(self) -> bool:
        return self.base_resolver is not None and self.base_resolver.is_async
```
2.  Even if `base_resolver` was correctly populated, it would still fail to be recognized as async by strawberry because: 

```python
@cached_property
def is_async(self) -> bool:       
    return iscoroutinefunction(self._unbound_wrapped_func) or isasyncgenfunction(
         self._unbound_wrapped_func
    )
``` 
the above piece of code from strawberry's `resolver.py` will evaluate to False for functions wrapped with `@sync_to_async`

If you take a look into strawberry's `extensions/field_extensions.py` in `build_field_extension_resolvers` you will see that when `field.is_async` evaluates to `False` we land to this piece of code: 

```python
if len(non_async_extensions) == found_sync_only_extensions:
    # Prepend sync to async extension to field extensions
    return list(
        itertools.chain(
            _get_sync_resolvers(field.extensions[:found_sync_extensions]),
            [SyncToAsyncExtension().resolve_async],
            _get_async_resolvers(field.extensions[found_sync_extensions:]),
        )
    )
``` 

However the resolver that was wrapped with `@sync_to_async` is in essence an asynchronous function and adding `[SyncToAsyncExtension().resolve_async]` to the chain will lead to the following exception being thrown upon execution of the mutation: 

` Expected value of type 'SomeType' but got: <coroutine __call__>.`
 
## System Information
 ```bash 
Linux localhost.localdomain 6.5.9-1-default #1 SMP PREEMPT_DYNAMIC Wed Oct 25 10:31:37 UTC 2023 (29edc7c) x86_64 x86_64 x86_64 GNU/Linux
```
 - Strawberry version (if applicable):
 
```toml
[tool.poetry.dependencies]
python = "^3.10"
strawberry-graphql = "^0.215.1"
strawberry-graphql-django = "^0.27.0"
```

## Additional Context

As a work around for this problem I forced `field.is_async = True ` in the extensions `apply` method, but this just a temporary fix and feels like a bad way to resolve this.

**Comment by bellini666** [comment]
Hey @m4riok ,

Do you have a small reproduction issue for this? It would help me a lot to try to understand what might be going on here

**Comment by m4riok** [comment]
Hey @bellini666, 

Sure, here is a minimal reproduction of this running under uvicorn: 

- urls.py

   ```python
    urlpatterns = [    
        path("graphql/", AsyncGraphQLView.as_view(schema=schema, graphiql=False)),
    ]
   ```
- models.py
    ```python
    class Test(models.Model):
        name = models.CharField(max_length=100)    
    ```
- schema.py
    ```python
    @strawberry_django.type(Test)
    class TestType:
        id: ID  # noqa: A003
        name: auto


    @strawberry_django.input(Test)
    class TestInput:
        name: auto


    class TestContextExtension(FieldExtension):
        async def resolve_async(self, next_: Callable[..., Any], source: Any, info: Info, **kwargs):
            cnt = await Test.objects.acount()
            return await next_(source, info, **kwargs)


    @strawberry.type
    class Query:
        Test: TestType = strawberry_django.field()
        Tests: list[TestType] = strawberry_django.field()


    @strawberry.type
    class Mutation:
        create_test: TestType = strawberry_django.mutations.create(
            TestInput, extensions=[TestContextExtension()]
        )

    schema = strawberry.Schema(
        query=Query,
        mutation=Mutation,
        extensions=[
            DjangoOptimizerExtension,
        ],
    )
    ```

And when executing the mutation: 
```graphql
mutation {
  createTest(data: { name: "string" }) {
    id
    name
  }
}
```
We get:
```json
{
  "data": null,
  "errors": [
    {
      "message": "Expected value of type 'TestType' but got: <coroutine __call__>.",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "createTest"
      ]
    }
  ]
}
```

And if we try defining a `resolve` method in the Extension Class like so: 
```python
class TestContextExtension(FieldExtension):
    def resolve(self, next_: Callable[..., Any], source: Any, info: Info, **kwargs):
       cnt = Test.objects.count()
       return next_(source, info, **kwargs)
```

Then we get: 
```json
{
  "data": null,
  "errors": [
    {
      "message": "You cannot call this from an async context - use a thread or sync_to_async.",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "createTest"
      ]
    }
  ]
}
```

Finally if the extension implements both resolve and resolve_async then the resolve will be entered even though we are running under asgi, within an event loop and with an async graphql view. This shouldn't be the case because resolver for the mutation is asynchronous because if I read your code correctly it is wrapped with `@sync_to_async` when running within an event loop.

Further more if you attach a break point within strawberry's `extensions/field_extensions.py` on line 87 inside `build_field_extension_resolvers` during schema conversion, and inspect the value of field you will notice that the value of `base_resolver` is `None`  which will mean that `field.is_async` will return `False` and cause all of these problems. 

But like I said in my original message even if you set base_resolver to point to your resolver which is wrapped with `@sync_to_async` you still have to deal with the fact that strawberry won't recognize wrapped functions as async.   

Hope this helps you find a work around for this. If you want more context feel free to ask or even contact me on discord.
