### ISSUE TITLE
Select/prefetch related fields with async query.

### ISSUE THREAD

**Issue by Ivan-Vinitskyi** [strawberry-graphql/strawberry-graphql-django#455]
## Field cannot be both deferred and traversed using select_related at the same time.

While trying to use `select_related` in `@strawberry_django.type` decorator I am getting this error:
```
Field Product.type cannot be both deferred and traversed using select_related at the same time.
```

I am using a chained relations in my models like this:
`Cart--CartItem--Product--ProductType `
and appropriate `strawberry_django.type`s chain, i.e.:
```
@strawberry_django.type(models.Product, select_related="type")
class ProductType:
    name: strawberry.auto
    description: strawberry.auto
    sku: strawberry.auto
    
    @strawberry.field(name="type", description="Ecom Product Type code")
    async def _type(self) -> str:
        return self.type.code
   
@strawberry_django.type(models.CartItem)
class CartItemType:
    product: ProductType
    quantity: strawberry.auto
    price: strawberry.auto
    meta: strawberry.auto


@strawberry_django.type(models.Cart)
class CartType:
    items: typing.List[CartItemType]
    total: strawberry.auto
```

in addition, there is an async version of queries/mutations like this:
```
@strawberry.field
    async def cart(...) -> CartType: ...
```

The problem is resolved just if I prepare the queryset on the top level in query with all possible (which could be requested) selected and prefetched models.
```
@strawberry.field
    async def cart(...) -> CartType: 
    return await Cart.objects.select_related(...).prefetch_related("cart_items__product__product_type").aget(...)
```

## System Information

 - Operating system: MacOS 14.2.1
strawberry-graphql = "0.209.2"
strawberry-graphql-django = "0.19.0"
django="4.2.9"

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/455">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/455/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/455/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @Ivan-Vinitskyi ,

First of all, any reason for you to be declaring the `select_related` at type level? Like, if you did that at field level where you access it, does it solve the issue?

Even if it does, this is still an issue that I want to take! Just mentioning in case this serves as a workaround for you

**Comment by Ivan-Vinitskyi** [comment]
> Hey @Ivan-Vinitskyi ,
> 
> First of all, any reason for you to be declaring the `select_related` at type level? Like, if you did that at field level where you access it, does it solve the issue?
> 
> Even if it does, this is still an issue that I want to take! Just mentioning in case this serves as a workaround for you

@bellini666 could your clarify please?
Do you mean this way:
```
@strawberry_django.field(select_related="...", prefetch_related="...")
async def cart(...) -> CartType: 
    return await Cart.objects.aget(...)
```
?
Actually this is the same as my current decision (just like a syntax sugar). But I hope we can setup all relation between connected strawberry_django type and then tweak them from the different top level queries (`@strawberry_django.field`) without explicit selecting/prefetching. Maybe DjangoOptimizerExtension could help, but it didn't worked as I expect here.

**Comment by bellini666** [comment]
@Ivan-Vinitskyi not really, what I mean is instead of this:

```python
@strawberry_django.type(models.Product, select_related="type")
class ProductType:
    name: strawberry.auto
    description: strawberry.auto
    sku: strawberry.auto
    
    @strawberry.field(name="type", description="Ecom Product Type code")
    async def _type(self) -> str:
        return self.type.code
````

doing this:

```python
@strawberry_django.type(models.Product)
class ProductType:
    name: strawberry.auto
    description: strawberry.auto
    sku: strawberry.auto
    
    @strawberry_django.field(
        name="type",
        description="Ecom Product Type code",
        select_related="type",
    )
    async def _type(self) -> str:
        return self.type.code
```

Maybe you would even need to do this TBH:

```python
@strawberry_django.type(models.Product)
class ProductType:
    name: strawberry.auto
    description: strawberry.auto
    sku: strawberry.auto
    
    @strawberry_django.field(
        name="type",
        description="Ecom Product Type code",
        select_related="type",
        only="type__code",
    )
    async def _type(self) -> str:
        return self.type.code
```

**Comment by Ivan-Vinitskyi** [comment]
@bellini666 thank you. Really only this helped:
> ```python
> only="type" # or "type__code" to be strict
> ```

TBH I don't understand the implementation. It is not clear, why we have to use `only` for product.type in addition to `select_related`, where do you use the `deferring` implicitly?

**Comment by bellini666** [comment]
> @bellini666 thank you. Really only this helped:
> 
> > ```python
> > only="type" # or "type__code" to be strict
> > ```

Oh, believe it or not, I never noticed you can do ".only(related_field)" and it will act the same as including everything. This is useful when doing a "select_related" for it and not doing "only" in anything.

> 
> TBH I don't understand the implementation. It is not clear, why we have to use `only` for product.type in addition to `select_related`, where do you use the `deferring` implicitly?

It is because when you do ".only()" for anything in your model you also need to add anything you have on "select_related" to it, otherwise django understands you want to include it (when doing the select related) and also to defer it (by not including it on only).

Knowing that `only="type"` I'll try to fix this during the weekend :)

**Comment by Ivan-Vinitskyi** [comment]
@bellini666 could it be fixed outside optimizers too (as far as I understand we can use "select_related" etc in django_strawberry.type)?

**Comment by bellini666** [comment]
@Ivan-Vinitskyi ahh, I got you question now =P

Any hints you add on `strawberry_django.field`, `strawberry_django.type`, are used by the optimizer, and will only be used as long as it is [enabled](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/optimizer/#enabling-the-extension) =P
