### ISSUE TITLE
When foreign key points to settings.AUTH_USER_MODEL

### ISSUE THREAD

**Issue by star2000** [strawberry-graphql/strawberry-graphql-django#6]
In create mutation, `userId` should be optional. The default value is the current login user‘s id. only the super user has the right to set it.

In update and delete mutation, users can only modify or delete the foreign key value equal to user's id, except super user.

**Comment by la4de** [comment]
Isn't that application specific feature? I don't think API framework should take care of that?

It's possible add your own permission class with permissions_classes ModelResolver attribute and do validation there. You can use ModelPermission as an example from here: https://github.com/la4de/strawberry-graphql-django/blob/main/strawberry_django/permissions.py#L4

Another option is to override create method of ModelResolver and do validation there.

**Comment by star2000** [comment]
I think this is the default behavior that most developers need.
Maybe we can make an plugin like `LoginMutation` that is not enabled by default.

**Comment by la4de** [comment]
I like that idea of having extensions for the most common use cases. Another way to approach such feature is to design generic API which could be then used to configure that behaviour.

For example now we can override create, update and delete functions and add application specific logic there.

**Comment by la4de** [comment]
We are designing new API. Please take a look. This should be possible with that one by using pre_save hook.
