### ISSUE TITLE
Support django Choices for graphql enums

### ISSUE THREAD

**Issue by deibeljc** [strawberry-graphql/strawberry-graphql-django#65]
With django 3.0 came the choices model field type [See here](https://docs.djangoproject.com/en/3.0/ref/models/fields/#choices). It would be nice if this integration converted those values into an enum for us so we don't have to declare the same enum twice and the source of truth can remain the model.

E.G.

Declaration in model
```
class PlayerTypes(models.TextChoices):
    FA = "FA", "Free Agent"
    PermFA = "PermFA", "Permanent Free Agent"
    Signed = "Signed", "Signed"
    Inactive = "Inactive", "Inactive"
```

Example usage?
```
@strawberry.django.type(models.Player)
class Player:
    name: auto
    type = strawberry.enum(models.PlayerTypes)
```

**Comment by LucidDan** [comment]
So far, I've found this to work just fine, like so:

```
PlayerType = strawberry.enum(models.PlayerTypes)

@strawberry.django.type(models.Player)
class Player:
    name: auto
    type: PlayerType
```

**Comment by la4de** [comment]
@LucidDan, thanks for the tip.

@deibeljc, does this solution work for you?

**Comment by capital-G** [comment]
Works in the proposed way by @LucidDan  but should be documented somewhere.
