### ISSUE TITLE
Strawberry.enum does not return a valid class type

### ISSUE THREAD

**Issue by deibeljc** [strawberry-graphql/strawberry-graphql-django#66]
When defining an enum without the class definition since I am dynamically building it, I get

![image](https://user-images.githubusercontent.com/10842162/138124556-91d64416-473f-45ca-91fb-3c29b34cb1ab.png)

If I try to use strawberry.enum on the actual field I get

![image](https://user-images.githubusercontent.com/10842162/138124835-a3cc94a6-3db5-43ac-926a-1b8666f652b3.png)

**Comment by la4de** [comment]
@deibeljc, This seems to be generic `strawberry-graphql` issue and not related to the django integration. Please report this to the strawberry project if you agree that's the case.

https://github.com/strawberry-graphql/strawberry
