### ISSUE TITLE
Partial update fields do not support many-to-many relationships.

### ISSUE THREAD

**Issue by pgoy-dod** [strawberry-graphql/strawberry-graphql-django#67]
It appears that many-to-many relationships are not supported while using partial update mutation fields. An error is raised saying that `DjangoUpdateMutation` does not have the `is_relation` attribute.

With the following models, types, etc.:

```python
# models.py

class Fruit(models.Model):
    colors = models.ManyToManyField("Color")


class Color(models.Model):
    name = models.CharField(max_length=20)
```

```python
# types.py

@strawberry_django.type(Fruit)
class FruitType:
    id: auto
    colors: auto


@strawberry_django.input(Color)
class ColorInput:
    name: auto


@strawberry_django.input(Fruit, partial=True)
class FruitPartialInput:
    id: auto
    colors: List[ColorInput]
```

```python
# schema.py

@strawberry.type
class Query:
    fruits: FruitType = strawberry.django.field()

@strawberry.type
class Mutation:
    update_fruit: FruitType = strawberry_django.mutations.update(FruitPartialInput)


schema = strawberry.Schema(query=Query, mutation=Mutation)
```

i get this error (and stacktrace):

```pytraceback
Exception in thread django-main-thread:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/graphql/type/definition.py", line 767, in fields
    fields = resolve_thunk(self._fields)
  File "/usr/local/lib/python3.10/site-packages/graphql/type/definition.py", line 296, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/usr/local/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 296, in get_graphql_fields
    graphql_fields[field_name] = self.from_field(field)
  File "/usr/local/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 152, in from_field
    for argument in field.arguments:
  File "/usr/local/lib/python3.10/site-packages/strawberry_django/mutations/fields.py", line 38, in arguments
    return arguments + super().arguments
  File "/usr/local/lib/python3.10/site-packages/strawberry_django/filters.py", line 148, in arguments
    if self.is_relation is False:
AttributeError: 'DjangoUpdateMutation' object has no attribute 'is_relation'
```

**Comment by LucidDan** [comment]
You might be hitting an issue I had, where mutations.update() only works properly with a List return type.
I had the same error in a model with no relationships, and eventually figured out that if I changed the return type to List[obj], it fixed (worked around?) the issue:

```
@strawberry.type
class Query:
    fruits: FruitType = strawberry.django.field()

@strawberry.type
class Mutation:
    update_fruit: List[FruitType] = strawberry_django.mutations.update(FruitPartialInput)


schema = strawberry.Schema(query=Query, mutation=Mutation)
```

**Comment by la4de** [comment]
@pgoy-dod , does the change proposed by @LucidDan fix it?

We really should better job here and raise more descriptive error message.

**Comment by pgoy-dod** [comment]
@la4de sorry, i ran into this during a prototyping phase and went with a different solution after running into this issue (it was a dealbreaker for my project). The code is already gone.

I trust @LucidDan to not be lying, though, so a better error message or better documentation would probably be very helpful!

**Comment by Desttro** [comment]
> You might be hitting an issue I had, where mutations.update() only works properly with a List return type. I had the same error in a model with no relationships, and eventually figured out that if I changed the return type to List[obj], it fixed (worked around?) the issue:
> 
> ```
> @strawberry.type
> class Query:
>     fruits: FruitType = strawberry.django.field()
> 
> @strawberry.type
> class Mutation:
>     update_fruit: List[FruitType] = strawberry_django.mutations.update(FruitPartialInput)
> 
> 
> schema = strawberry.Schema(query=Query, mutation=Mutation)
> ```

Same issue for me (models without relations) and I can confirm, that when I change update and delete to List type, it works!
Thanks @LucidDan
