### ISSUE TITLE
Proposal: moving this repo to strawberry-graphql organisation

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry-graphql-django#7]
Hi @la4de! Thanks for making this package. Would you consider moving it to strawberry-graphql organisation? 

So we can adopt this as an official extension of strawberry (and maybe also introduce continuous releases).

Let me know what you think! :)

**Comment by la4de** [comment]
That would be great! I fully support that proposal.

**Comment by patrick91** [comment]
Awesome! Are you our discord channel? we can discuss there how to tackle this 😊https://strawberry.rocks/discord

**Comment by patrick91** [comment]
I'll close this as it is now done 😊
