### ISSUE TITLE
Setting Default Values for Filters

### ISSUE THREAD

**Issue by slee356** [strawberry-graphql/strawberry-graphql-django#71]
Hello,

How can I set default values for the filter on a query? I'd like to start `fruits` query with certain fruits (and certain colors, if possible) and let users to change the filters.

```python
@strawberry.type
class Query:
    fruits: List[Fruit] = strawberry.django.field()
```

**Comment by la4de** [comment]
Currently the only way to do this is to implement your own resolver and filtering logic.

For example in this way

```python
@strawberry.type
class Query:
    @strawberry.django.field()
    def fruits(my_filter: str = 'default value') -> List[Fruit]:
        return Fruit.objects.filter(name__contains=my_filter)
```

**Comment by slee356** [comment]
Thanks!
