### ISSUE TITLE
Docs references need to be updated

### ISSUE THREAD

**Issue by ccsv** [strawberry-graphql/strawberry-graphql-django#77]
So the examples on the github page uses  `strawberry.django` but the references use `strawberry_django` which is incorrect here:

https://github.com/strawberry-graphql/strawberry-graphql-django/tree/main/docs/references

**Comment by la4de** [comment]
Both are still working but I agree with you. We want to start using new `strawberry.django` syntax in documentation. Would you like to contribute and create a pull request? :)

**Comment by ccsv** [comment]
@la4de Sure I will take a stab at it

**Comment by ccsv** [comment]
Ok here is what I did https://github.com/strawberry-graphql/strawberry-graphql-django/pull/78

The other thing we might want to add is a way to secure the Graphql view page using `LoginRequiredMixin` . I have not tried it for strawberry but I did test and added this for graphene [a while ago](https://github.com/graphql-python/graphene-django/commit/84d82f82a91ba845e3070929c91156c769848d5c#diff-497275e24df8d2df0cde9b24fc93c26a01aa17ffa2526f0817ee21ae8e72b444)

**Comment by la4de** [comment]
GraphQL view currently comes from core package. Feel free to create a ticket under [strawberry](https://github.com/strawberry-graphql/strawberry) project. =)
