### ISSUE TITLE
"'ModelClass' object has no attribute 'all'"

### ISSUE THREAD

**Issue by joeydebreuk** [strawberry-graphql/strawberry-graphql-django#8]
Suppose this is also a feature request to support reverse relationships.

The code below causes: `'Profile' object has no attribute 'all'`

Query:
```
{
  users {
    id
    profile {
      id
    }
  }
} 

```

Schema:
```
class ProfileResolver(ModelResolver):
    model = Profile
    fields = (
        "id",
    )

class UserResolver(ModelResolver):
    model = User
    fields = (
        'id',
        'profile'
    )
    
@strawberry.type
class Query(
    UserResolver.query(),
):
    pass

@strawberry.type
class Mutation(
    UserResolver.mutation(),
):
    pass

schema = strawberry.Schema(query=Query, mutation=Mutation)
```

Models:
```
class Profile(models.Model):
    user = models.OneToOneField(
        User,  # Default Django User model
        unique=True,
        verbose_name=_("user"),
        related_name="profile",
        on_delete=models.CASCADE,
    )
```

And for someone running into this in the meantime, the following does work:

```
class ProfileResolver(ModelResolver):
    model = Profile
    fields = (
        "id",
    )


class UserResolver(ModelResolver):
    model = User
    fields = (
        'id',
    )

    @strawberry.field
    def profile(info, root) -> ProfileResolver.output_type:
        return root.profile
```

 Maybe the last snippet could be useful in the example.

If you would like me to create a PR for any of this, let me know.

**Comment by la4de** [comment]
One to one relation seems to be bug. I can take a look.

I agree with you that your example would be nice addition to the doc. Would like to open pull request for that? :)

**Comment by joeydebreuk** [comment]
Sorry for late reply. Will do

**Comment by joeydebreuk** [comment]
https://github.com/strawberry-graphql/strawberry-graphql-django/pull/9/files

**Comment by la4de** [comment]
I'm working on new API and therefore not planning to continue development of old API.
