### ISSUE TITLE
relay pagination

### ISSUE THREAD

**Issue by productdevbook** [strawberry-graphql/strawberry-graphql-django#81]
https://relay.dev/
Will you support relay pages?

cursor, is next etc

**Comment by bellini666** [comment]
Hey, just a quick heads up: I created a very generic relay implementation and also integrated it with strawberry django in here: https://github.com/strawberry-graphql/strawberry-graphql-django

**Comment by radekwlsk** [comment]
@bellini666 Are you interested in suggesting to merge that relay implementation with the `strawberry-graphql/strawberry-graphql-django` itself?

**Comment by bellini666** [comment]
@radekwlsk not actually. The relay implementation is generic and not attached to django at all, and thus it is being proposed to be merged here.

Having said that, I'm open to contribute any of the rest of the django specific code there, which also integrates that relay implementation automatically for django types, back to `strawberry-graphql-django`, as long as there's interest in it.

**Comment by la4de** [comment]
Right only offset pagination is currently supported by `strawberry-graphql-django`. I like the idea of pushing generic relay pagination to the strawberry core which can be then reused in django projects.
