### ISSUE TITLE
Filtering cannot use relational reflection fields

### ISSUE THREAD

**Issue by star2000** [strawberry-graphql/strawberry-graphql-django#84]
https://github.com/strawberry-graphql/strawberry-graphql-django/blob/7ec710bf62bd599442601d0a9605e7bedf1dfca1/strawberry_django/filters.py#L90-L92

`django_model._meta._forward_fields_map` should be changed to
```py
from django.db.models.sql.query import get_field_names_from_opts
get_field_names_from_opts(django_model._meta)
```

**Comment by la4de** [comment]
Could you describe you problem you are solving by suggesting this change? It would be good to understand the problem so that we can implement proper test case for that.

I agree with you that It's probably good idea to use django API for that.

**Comment by star2000** [comment]
.eg
```py
import strawberry_django
from strawberry_django import auto
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission

@strawberry_django.filters.filter(Permission, lookups=True)
class PermissionFilter:
    id: auto
    name: auto
    content_type: 'ContentTypeFilter'  # available
    codename: auto

@strawberry_django.filters.filter(ContentType, lookups=True)
class ContentTypeFilter:
    permission: 'PermissionFilter' # not available
    id: auto
    app_label: auto
    model: auto
```

**Comment by star2000** [comment]
Maybe I didn't show it clearly enough, see this

<img width="497" alt="image" src="https://user-images.githubusercontent.com/42126168/163665642-3ed43ff2-2db1-480a-8fa6-33ea2d616ca8.png">
