### ISSUE TITLE
[Bug] Authentication methods fail when trying to return None

### ISSUE THREAD

**Issue by LaughDonor** [strawberry-graphql/strawberry-graphql-django#85]
Using `0.3rc1` and when trying to log in:
1. The username must match exactly, or
2.  If the user doesn't exist

The backend will try to return `None`, but the schema doesn't allow this and provides the following rejection:
> "Cannot return null for non-nullable field Query.login."

I'm on a fresh project using Django 4.0.1

Here's my schema for the record, matching the demo and works fine with correct inputs and gives the above error otherwise:
```python
# schema.py
from strawberry import Schema, type as strawberry_type
from strawberry.django import auth

from .types import User, UserInput


@strawberry_type
class Query:
    login: User = auth.login()
    logout: bool = auth.logout()
    me: User = auth.current_user()


@strawberry_type
class Mutation:
    register: User = auth.register(UserInput)


schema = Schema(query=Query, mutation=Mutation)
```

When getting the output of `str(schema)`, I do see those resolvers returning "User!" instead of "User".

**Comment by g-as** [comment]
```
@strawberry_type
class Query:
    login: typing.Optional[User] = auth.login()
```
?

**Comment by LaughDonor** [comment]
Ohhh I knew I was missing something. Thanks!
