### ISSUE TITLE
Lookup fields not working

### ISSUE THREAD

**Issue by aareman** [strawberry-graphql/strawberry-graphql-django#86]
Thank you for this library. Really helpful, migrating from graphene-django.

i'm not sure how the lookups are supposed to work. 

```python
@strawberry.django.filters.filter(models.Submission, lookups=True)
class SubmissionFilter:
    updated_date: date
    updated_date__lte: date
    updated_date__gte: date
```

It creates the types, but doesn't actually filter by the lookups. The plain singe date filter works as expected.
![image](https://user-images.githubusercontent.com/10500823/150548401-5886769e-eb61-4ced-80e7-8e1c0e45de22.png)

**Comment by aareman** [comment]
They are all `date` types

**Comment by aareman** [comment]
That is Sweet! Thank you for the quick response

I was stepping through the code and realized it was being swallowed in the 
![image](https://user-images.githubusercontent.com/10500823/150556138-aa0784cd-0f5b-4888-ac29-08ddb94b8942.png)
conditional. Since `updated_date__lte` didn't exist on the model. I added a `re.sub` on it to strip the `__[a-z]*$` from it, and then it worked in the format i was doing. Do you think that format would be good support as well, so that you can filter, but restrict  the lookups to specific types per field.

The current solution hands all the lookups to the user, which may not be what every case warrants, but is really clean IMO.

I guess drilling further down into the graphql inspection docs would've helped me out, I just didn't expect it to hand you all the lookups automatically.

**Comment by aareman** [comment]
I just tried out using `auto` as a type, but getting 

TypeError: SubmissionFilter fields cannot be resolved. Unexpected type '<class 'strawberry_django.fields.types.auto'>'

**Comment by la4de** [comment]
Thanks for your feedback. I agree with you that it would be nice to have possibility to define which lookups to include to your filter. I'm not sure yet how would that API look like.

Adding support for `auto` type is good idea!

**Comment by la4de** [comment]
We have a test case for `auto` type in filters. See https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/tests/filters/test_filters.py#L12-L15

Could you share the code which is failing?

**Comment by aareman** [comment]
See above code snippets

**Comment by bellini666** [comment]
Hey @aareman ,

It's been a while since you reported this issue, and since then strawberry-django has gone through a major refactor.

This issue should be fixed and working correctly in the current version, so I'm going to close this. If it is not, please tell me so I can reopen the issue
