### ISSUE TITLE
Question: apply filters in 'custom' resolver

### ISSUE THREAD

**Issue by gersmann** [strawberry-graphql/strawberry-graphql-django#92]
Hi, thank you for the library. This is a question rather than an issue. If I implement a custom resolver, is there a way to 'reuse' the functionality of applying the filters to a base queryset in some way?

**Comment by la4de** [comment]
Example for that pushed to repo.
https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/tests/filters/test_filters.py#L138-L151

**Comment by gersmann** [comment]
Very nice, thanks a lot.

**Comment by jcuenod** [comment]
For posterity: https://github.com/strawberry-graphql/strawberry-graphql-django/commit/98edfa4d8032f19570b21aa252a2e57e3c78c9e4
