### ISSUE TITLE
Ordering not in schema when passing via decorator

### ISSUE THREAD

**Issue by jaydensmith** [strawberry-graphql/strawberry-graphql-django#96]
In the example you can pass `order` into the Django type decorator, the result however has the order argument missing from the schema. Filter and pagination work fine.

https://github.com/strawberry-graphql/strawberry-graphql-django/blob/674c7b914611e0cc798d0b9480a207220b2d3433/examples/django/app/types.py#L46-L52

Currently I am working around this by defining the order at the field definition:
```python
@strawberry.type
class Query:
    fruits: List[Fruit] = strawberry_django.field(
        filters=FruitFilter,
        order=FruitOrder,
        pagination=True
    )

**Comment by bellini666** [comment]
Fixed by https://github.com/strawberry-graphql/strawberry-graphql-django/pull/176
